### ISSUE TITLE
.map.zip maps arent shown in the Map Menu

### ISSUE THREAD

**Issue by DeSchmiddi** [OpenTracksApp/OSMDashboard#104]
I tried to extract them, to which both winrar and 7zip said that they were not zip files. So I figured, that, perhaps, I need to place them there as zip files. I installed themes, too and they are also in .zip format and not found.

Thanks in advance!

**Comment by pstorch** [comment]
The app only looks for .map files it can't read/extract .map.zip files. For themes it searches for .xml files or directories which contain a .zip file with the same name as the directory.

**Comment by DeSchmiddi** [comment]
.map.zip and .xml are what openandromaps gives you for maps and themes respectively.

Theme: https://www.openandromaps.org/wp-content/users/tobias/Elevate.zip
Map:https://ftp.gwdg.de/pub/misc/openstreetmap/openandromaps/mapsV4/Germany/baden-wuerttemberg.zip

It is a page that you specifically link to as a source for maps. Should I just remove the .zip, since it cant be extracted, and create an .xml for the theme? if yes, how?

**Comment by pstorch** [comment]
Hmm, strange that you cannot extract them. I can extract them with  ArchiveManager on Linux or with the Filemanager on Android. So I assume it is a valid .zip file.

I must admit that the integration with openandromaps is not very comfortable. 
I'm thinking about implementing support for `mf-v4-map://`and `mf-theme://` URLs.

**Comment by pstorch** [comment]
As @dennisguse pointed out, there is support for themes in .zip files in the new mapsforge library. I'll have a look into it. As far as I could see, a theme .zip file can contain several themes, so I need a selection.

I didn't see support for .map.zip, so I think the App would need to extract them to be able to use them. Let's see, what I can do. I'm interested in supporting those download URIs.

**Comment by pstorch** [comment]
Support for themes in .zip files will come with the next release.
Map .zip files are not supported by mapsforge library. I'm looking into listening on those URLs and download and extract those maps.

**Comment by pstorch** [comment]
Support to download Maps and Themes directly from Mapsforge, Freizeitkarte and Openandromaps websites including the zipped map files is implemented. Coming in the next release.

**Comment by pstorch** [comment]
@DeSchmiddi do you like to give the new functionality a try? With the new version you should be able to click on the download links of OpenAndroMaps or Freizeitkarte and download the maps and themes directly with the OSMDashboard app.

Here is the debug version for testing:
https://cloud.railway-stations.org/index.php/s/iFb4Etne9STgpcp

**Comment by dennisguse** [comment]
@pstorch FYI: you can upload an APK to Github if you zip it. :sunglasses:

**Comment by DeSchmiddi** [comment]
@pstorch I'll try it our as soon as I can, right now I am on holiday in a foreigin country with expensive roaming. Thanks very much!
