### ISSUE TITLE
Crashes when typing on map directory button

### ISSUE THREAD

**Issue by bmrpiastc** [OpenTracksApp/OSMDashboard#108]
When I type on the map directory button, the app crashes. I suggest it is caused by the not allowed permission of the device storage. It can not be changed, because the application does not “want” this permission. I’ve tried it with adb, but it return the same error.
I am using android 10 and armv8. 
Thanks for your support!

**Comment by pstorch** [comment]
Thanks for reporting. So you have exact steps to reproduce it? Normally the app should ask for a new directory if the old one becomes unavailable.

The app doesn't require general storage permission, but asks other apps (e.g. file managers) for a directory to use.
What directory was it previously? A normal directory from the local file system, a temporary directory from an SD card or USB drive? Or a remote directory from an app like Nextcloud, Gdrive or OneDrive?

**Comment by pstorch** [comment]
@bmrpiastc reading your description again: maybe I misunderstood. Is it the first time you click on the map directory menu button in the app?

**Comment by bmrpiastc** [comment]
Thank you response!
As you mentioned, the OSMDashboard needs a file manager for this function. This was the problem, because I deactivated the standard files application and used Simple File Manager Pro as my file manager. This does not work for this funktion of OSMDashboard.

**Comment by pstorch** [comment]
@bmrpiastc thanks for the information. That explains it. I don't know how you managed to disable the file manager app. I was not able to do it on my phone nor on any emulater I have. But I've implemented a catch for the ActivityNotFoundException. I hope the app doesn't crash anymore in this situation.

Would be nice if you can test the fix as I'm not able to reproduce it.

[OpenTracksOSMPlugIn-full-debug.zip](https://github.com/OpenTracksApp/OSMDashboard/files/6950393/OpenTracksOSMPlugIn-full-debug.zip)

**Comment by bmrpiastc** [comment]
@pstorch thank you very much for the fix of this issue. The file you uploaded works out and reports the error “No file manager found” without crashing. On my device (LG K61 (LM-Q630EAW)) it is a little strange, because there are several “system apps” like LG Music which can not be disabled via the setting without root acess, in difference to the files application.

**Comment by pstorch** [comment]
Cool, thanks for testing.
