### ISSUE TITLE
Fastlane descriptions

### ISSUE THREAD

**Issue by IzzySoft** [OpenTracksApp/OSMDashboard#11]
Could you please update Fastlane description?

* The `short_description` should not be longer than 80 chars, everything beyond that is truncated (see the F-Droid listing) – I'd suggest leaving the URL out there
* `full_description` could be formatted to look better. Suggestion:

```html
<p>An OpenStreetMap dashboard for <a href="https://github.com/OpenTracksApp/OpenTracks">OpenTracks</a>. It simply shows a selected track with start- and endpoints on a map from OpenStreetMap.</p>
<p>The default is an online map, but offline maps are supported as well. With offline maps, there is no necessity for mobile data.</p>
```

While on it, some screenshots would be really helpful. I would have provided you the corresponding Fastlane tree, but could not (see #10).

Thanks!

**Comment by pstorch** [comment]
Thanks for reporting. I'll amend it.

**Comment by pstorch** [comment]
@IzzySoft I would like to add some more details in the full description. Where can I find which html tags are supported? I'm searching here: https://f-droid.org/en/docs/Build_Metadata_Reference/#Description but couldn't find it.

**Comment by IzzySoft** [comment]
Not sure, I'd say "try-and-err". Think of the "sane tags" logic used in several places for user comments. Some I do know to work include:

* p
* ol, ul, li
* font color=

Javascript is certainly forbidden. (`grep`ing the source) Ah! The other way around: [forbidden HTML tags](https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/lint.py#L176), those two lines should answer your question I'd say :wink:

PS: Added that hint to my snippet describing the [Fastlane file structure](https://gitlab.com/snippets/1895688) – a short reference you might find useful.

**Comment by IzzySoft** [comment]
Cool, thanks! I've just commented the diff for some minor corrections.

**Comment by pstorch** [comment]
@IzzySoft the new description is live now. The paragraphs have lots of whitespace. Is there something I can do about?

![image](https://user-images.githubusercontent.com/5598124/73429406-ead23e80-433b-11ea-95d8-24a1c5287f14.png)

**Comment by IzzySoft** [comment]
Urgs. Looks like the formatter still inserts a `<br>` for each line-break (not just for empty lines as I remembered it). You could try removing the wrapping `<p>`s (sorry for introducing them – that's how I did it in the past, must have missed something). Taking the initial example again:

```html
An OpenStreetMap dashboard for <a href="https://github.com/OpenTracksApp/OpenTracks">OpenTracks</a>. It simply shows a selected track with start- and endpoints on a map from OpenStreetMap.
The default is an online map, but offline maps are supported as well. With offline maps, there is no necessity for mobile data.
```
