### ISSUE TITLE
Show more tracks?

### ISSUE THREAD

**Issue by jensMF** [OpenTracksApp/OSMDashboard#13]
In OpenTracks it is possible, to select more tracks and then tap on the maps icon. The dashboard opens, but only one track is shown.
It would be great, if all tracks selected would be shown.
Then it would be neccessary to have different colors for different tracks of course …

Just an idea I would find nice.

**Comment by pstorch** [comment]
Makes sense to me.

@dennisguse is it possible to add a list of track IDs to the URL?

**Comment by dennisguse** [comment]
At least showing should already the trackpoints should already be possible, as this information is transmitted as part of the TrackPointsColumns: https://github.com/OpenTracksApp/OpenTracks/blob/df502f835c585433bea6735e21bfa5c8b61a8be0/src/main/java/de/dennisguse/opentracks/content/data/TrackPointsColumns.java#L38

And also providing multiple tracks would be possible - at the moment, the URL only contains one track (I hope, I recall that right).
@jensMF The actual question is if this feature is really important.

**Comment by jensMF** [comment]
For me it is important. But I can not tell for how many people it might be … I would use and recomment these apps, if this feature would be existent.
In the mantrailing trainings I have with my Team, it is important to have all tracks on the map, to know, where someone went, and where it is free, to plan the next/other tracks.

**Comment by dennisguse** [comment]
@jensMF if you do not use the Dashboard (deinstall and use OSMAnd) that would be working (no live updates though).

@Pstorch: we could either provide more URLs (easy in OpenTracks) or provide one custom URL ( more effort in OpenTracks).
But I have no time until March....

**Comment by pstorch** [comment]
I found a way to forward multiple tracks to the dashboard:
https://github.com/OpenTracksApp/OpenTracks/pull/133

The idea is to have a comma separated list of TrackIds.
@dennisguse please have a look. If this approach is ok, I could work on the dashboard to show the different tracks in different colors.

**Comment by pstorch** [comment]
As a side effect: when we show multiple tracks and want to implement #4 to show some track statistics. Would that mean to calculate an overall statistic (e.g. averaging all values)?

**Comment by dennisguse** [comment]
The computation is done per track.
An overall computation would need to be done in the Dashboard I guess.

**Comment by pstorch** [comment]
I started to separate multiple tracks by color. At first I tried different shades of blue, but the more tracks are displayed the harder is it to distinguish. I need to put some thought into proper coloring of the tracks. Ideas welcome ;)

**Comment by dennisguse** [comment]
@pstorch About the coloring; some time ago I had the same problem for a standalone web application that presents geo data.
For reference: https://github.com/dennisguse/thekarte

The actual code is here (it is JavaScript but not rocket science): https://github.com/dennisguse/TheKarte/blob/master/src/StyleColorCreator.js

**Comment by pstorch** [comment]
@dennisguse nice, thanks. Copied and adapted :wink:

**Comment by pstorch** [comment]
Waiting for https://github.com/OpenTracksApp/OpenTracks/pull/133

**Comment by pstorch** [comment]
Will be possible with next release of OpenTracks + Dashboard.
