### ISSUE TITLE
Show viewing direction on map (via compass)

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OSMDashboard#14]
Since OSMDashboard get live updates from OpenTracks showing the current viewing direction (arrow) at the current (last received from OpenTracks) position.

For the data collection, I actually plan plan to collect this data in OpenTracks.
However, it will only be stored when new GPS coordinates are received and thus might not be sufficient for a live UI (at least not via the current TrackPoint-URI approach).
See: https://github.com/OpenTracksApp/OpenTracks/issues/2

**Comment by dennisguse** [comment]
While using, OSMDadhboard: this feature is really important to me. Also, we could remove the marker for the start point.

**Comment by pstorch** [comment]
I still don't have a clear understanding of this feature. Do you want to have an arrow at the last trackpoint instead of a circle? Which direction should it have? Calculated from the second to last trackpoint to the last or use the live device orientation?

Removing the start circle could be easily implemented or made an optional config.

**Comment by dennisguse** [comment]
Exactly: an arrow at the last trackpoint that shows the direction derieved from the compass.
However, this information cannot be retrieved from OpenTracks.
At the moment, the compass is not yet used in OpenTracks (I have it on the roadmap).
In addition, track points are (so far) only inserted (using most recent data available, but not updated.
The actual question is: which app is responsible for getting listening to compass-changed events?
What we could do in OpenTracks is listen for compass-changed events and pass it to the Dashboard (some kind of virtual column at the track?) while only storing it when a new track point is inserted.
I want to avoid having useless writes on the SQLlite DB (I don't know it handles this - in terms of actual writes to disk).

Some thoughts :)

**Comment by pstorch** [comment]
I could read the Device orientation sensor and rotate the arrow accordingly.

**Comment by dennisguse** [comment]
Or just using https://developer.android.com/reference/android/hardware/Sensor.html#TYPE_MAGNETIC_FIELD


The orientation sensor is a virtual one combining compass+acceleration+gyro.

https://developer.android.com/reference/android/hardware/Sensor.html#TYPE_ORIENTATION

Whatever is better :)

**Comment by pstorch** [comment]
I've experimented a bit. Showing an arrow at the last position with the viewers direction was a bit difficult. The map was redrawing a lot and freezing from time to time. Also the viewers direction confused me a lot. 
What I came up with was a ImageView on top of the map in the upper right corner showing north, like a compass rose. What do you think?

<a href="http://www.youtube.com/watch?feature=player_embedded&v=CHlQfJpK1EE 
" target="_blank"><img src="http://img.youtube.com/vi/CHlQfJpK1EE/0.jpg" 
alt="Compass rose in OSM Dashboard" width="240" height="180" border="10" /></a>

**Comment by dennisguse** [comment]
Nice!!! That's a really cool solution! I must admit that I thought this functionality would be available in Mapsforge.

**Comment by pstorch** [comment]
fixed via d35e558a1f0267eca5f137104610041832bc523f
