### ISSUE TITLE
Migrate to Storage Access Framework

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OSMDashboard#15]
Storage Access Framework is the new way to access storage rather `READ_EXTERNAL_STORAGE` (deprecated as of Android 29 requiring a legacy flag).

PS: Not important / urgent; just to keep it in mind :)

**Comment by pstorch** [comment]
Something I need to look into.

**Comment by pstorch** [comment]
Recently I wanted to import gpx files I once exported from OpenTracks (pre Storage Access Framework) from the external storage, but I wasn't able to access them anymore. Only the Documents folder and some Cloud Apps were selectable. I had to copy the old OpenTracks/gpx directory manually below Documents. 
This seems very limiting. If we implement this in the Dashboard, one would not be able to reuse the maps from another app like Locus Maps, which stores the offline maps on the external storage.

**Comment by dennisguse** [comment]
Mhh.
That should actually not be an issue - at least on my LineageOS devices everything is expected.
So, I can select all folders (internal and external storage that is user accessible) and can import export.
BUT at least in the LineageOS: the selection dialog is not that intuitive as you have to select the root directory (e.g., harddrive) via the hamburger menu.

And you can also send the files directly to (and from) any storage provider like Nextcloud.

**Comment by pstorch** [comment]
Ah, sorry. Now I see how to change to all other directories.

**Comment by dennisguse** [comment]
@pstorch

>  It's feature not a bug.

**Comment by pstorch** [comment]
Looks like with the current mapsforge library this is not possible. The MapFile class needs a java File object and can't work with DocumentFile nor Uri nor InputStream. :confused:

**Comment by dennisguse** [comment]
Just a quick guess: MapFile accepts FileInputStream.
And you can get one from DocumentFile via 
pfd = context.getContentResolver().openFileDescriptor(treeUri, "rw"); FileInputStream fis = new FileInputStream(pfd.getFileDescriptor());

Would this work?

**Comment by pstorch** [comment]
Good idea, but results in a bad file descriptor:

```
E/MapFile: Bad file descriptor
    java.io.IOException: Bad file descriptor
        at sun.nio.ch.FileChannelImpl.position0(Native Method)
        at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:327)
        at org.mapsforge.map.reader.ReadBuffer.readFromFile(ReadBuffer.java:125)
        at org.mapsforge.map.reader.MapFile.processBlocks(MapFile.java:606)
        at org.mapsforge.map.reader.MapFile.readMapData(MapFile.java:928)
        at org.mapsforge.map.reader.MapFile.readMapData(MapFile.java:889)
```

**Comment by dennisguse** [comment]
Mhh. MapsForge had a related change: https://github.com/mapsforge/mapsforge/issues/982

This added a FileChannel constructor.
And this can be derived from a FileInputStream?

**Comment by pstorch** [comment]
When I get the channel from the FileInputStream I get the same error as above.

**Comment by dennisguse** [comment]
:( 
How are you getting the file descriptor from the DocumentFile?

**Comment by pstorch** [comment]
```
            ParcelFileDescriptor parcelFileDescriptor =
                    getContentResolver().openFileDescriptor(mapFileUri, "r");
            FileDescriptor fileDescriptor = parcelFileDescriptor.getFileDescriptor();
            return new MapFile(new FileInputStream(fileDescriptor).getChannel(), 0, null);

```

**Comment by dennisguse** [comment]
Or a filechannel can be derived from an inputstream: https://stackoverflow.com/questions/6619516/using-filechannel-to-write-any-inputstream

**Comment by pstorch** [comment]
`Channels.newChannel(inputstream)` returns a `ReadableByteChannel` which is not a `FileChannel`

**Comment by pstorch** [comment]
Discussion on the Mapsforge Forum: https://groups.google.com/forum/m/#!topic/mapsforge-dev/2tkZjOx8tdQ

**Comment by dennisguse** [comment]
Mhhh. It sounds as if it would be feasible, but I don't know why the file descriptor is not accepted. I also did not found any alternative solution. And I don't know what the alternative would be. 
@pstorch What kind of inputstream do you get using getContentResolver().openInputStream()? Could it be cast to something useful?

**Comment by pstorch** [comment]
![image](https://user-images.githubusercontent.com/5598124/75633778-4841ff80-5c08-11ea-8833-761a739844dc.png)

**Comment by pstorch** [comment]
I think I got it 🎉

**Comment by dennisguse** [comment]
@pstorch and?

**Comment by pstorch** [comment]
I could cast the InputStream to a FileInputStream and give it to MapFile. Then I had to fix something with the MapThemes as well.
