### ISSUE TITLE
Upgrade to OpenTracks 4.0.0 style?

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OSMDashboard#151]

**Comment by pstorch** [comment]
Good idea

**Comment by pstorch** [comment]
Related PRs from OpenTracks:

- https://github.com/OpenTracksApp/OpenTracks/pull/1133
- https://github.com/OpenTracksApp/OpenTracks/pull/1155

**Comment by khao-soi** [comment]
Can we change the pushpin (ic_marker_orange_pushpin_with_shadow) to something more modern when doing that? This thing is not quite eye candy =)

**Comment by pstorch** [comment]
@khao-soi sure, any suggestion? PullRequest welcome. Or post an icon here in the comments and I'll integrate it.

**Comment by khao-soi** [comment]
@pstorch https://github.com/OpenTracksApp/OSMDashboard/pull/248
