### ISSUE TITLE
All map tiles not displayed properly

### ISSUE THREAD

**Issue by crankc** [OpenTracksApp/OSMDashboard#160]
White squares are often displayed around the map, sometimes flashing and disappearing when moving around the map, sometimes staying, as per attached screenshot. The squares disappear again when zooming in or out.

- OSM Dashboard (offline) v2.15.0
- Pixel 5 running Android 12 (LineageOS 19.1)
- Map download source seems irrelevant, result is the same for any map or theme i could find. The map in the screenshot is from Freizeitkarte.

![Screenshot_20220702-073254_OSM Dashboard (Offline)](https://user-images.githubusercontent.com/105491401/176986748-b10753d6-aef4-4d84-aa9a-e4e0d001fb8d.jpg)

**Comment by pstorch** [comment]
I have that sometimes, too. Haven't figured out why this happens. Can you try to change the "Multithread map rendering" option if this changes anything on your device?

**Comment by crankc** [comment]
I tried that and it makes no difference whether it's enabled or disabled. Might be a Mapsforge issue? I searched through their tickets and found nothing, though.

**Comment by pstorch** [comment]
There are a few closed ones: https://github.com/mapsforge/mapsforge/issues?q=is%3Aissue+blank+tiles+is%3Aclosed

As far as I understood it could be this multithreadding, or memory issues on the device or device is busy with other tasks or a buffer size.

**Comment by dennisguse** [comment]
For me this happens actually quite frequently (with/-out multithreading); somehow I got used to it (sadly).
Anyhow, issues seems to appear and also disappear during (re-)rendering (i.e., scrolling, zooming, opening menu).
Somehow mapsforge thinks it is done with rendering, but isn't.

Data is definitely okay as the tiles will be rendered later (and I only downloaded them once).

**Comment by dennisguse** [comment]
@pstorch just a really quick guess: might the TileCache be an issue?
If I understood it correctly, it caches on external storage.
And is it really that useful (if the device is powerful enough)?

**Comment by pstorch** [comment]
Maybe the TileCache plays a role as well.

**Comment by pstorch** [comment]
Removing the TileCache is not an option, it is necessary. But there is a parameter to disable the persistence. I've added an option into the advanced menu to disable TileCache persistence. Then I've also added an option to purge the Cache. Maybe this can help in some situations as well.

Can be tested with the latest nightly:
https://fdroid.storchp.de/fdroid/repo/

At the moment it works either way on my device, so it's hard to test for me. But I'm looking forward to hearing from you.
BTW: there is also an update of the mapsforge lib in the nightly. I don't know if this has an impact as well.

If it is still an issue, there are more parameters to play with. For example we could change (or configure) the overdrawFactor which also has an impact on the TileCache and the rendering in general.

**Comment by gdt** [comment]
I'm unclear on the details so take this with  a grain of salt, but last time I looked at the OSM tile usage policy, there was  a requirement to cache with a minimum time of 7 days, or somethign like that.

**Comment by pstorch** [comment]
You are right, this is applicable for the online tiles.
Maybe I should add an explanation to this option, before releasing.
But for offline maps we are completely free.
The persistent option is also only for the second level cache. So there is still the first level cache. We can also experiment with the first level cache size.

**Comment by crankc** [comment]
@pstorch Unfortunately the issue persists in the nightly build, whether persistence is toggled on or off. Purging the cache flashes the white tiles away but they return almost immediately.

This occurs on both online and offline map source, it seems.

**Comment by pstorch** [comment]
Hmm, ok. Thanks for testing. Need to try other options.

**Comment by dennisguse** [comment]
Same for me.
Additional observations: 
* no logcat messages are shown (only Dashboard started) => no error messages
* online maps: 
  * it seems as if always the same tile(s) were broken (for testing Schildow; north of Berlin); only on one zoom level
  * purge cache actually reloaded everything correctly and then some tiles vanished again (on rerender?)
* offline maps
  * it seems as if always the same tile(s) were broken (for testing Schoenfliess; north of Berlin); only on one zoom level
  * zooming in (ok); going back to the previous zoom level: same tiles broken again
  * purge cache actually reloaded everything correctly and then some tiles vanished again (on rerender?)

Assumptions:
* data is available on the device (either online or offline): yes, as purging cache shows it

Hypothesis:
* problem while rendering?
* problem due to caching?

... at least a problem in caching would explain why the same tiles are affected.

How do we get logs out of mapsforge?

PS/ tested online and offline maps separately, but it felt very similar in the observed behaviors.
But the rendered online maps and offline maps have a different style.

**Comment by pstorch** [comment]
Another try. This time the map overdraw factor is configurable in the advanced menu. Default is 1.4, but you can choose between 1 and 2. Restart the app after changing the setting.
I could find a few settings where I also get blank tiles. Let's see if you can find values which work for you without blank tiles.

**Comment by dennisguse** [comment]
FYI I asked mapsforge how to debug this.
https://github.com/mapsforge/mapsforge/discussions/1331

**Comment by crankc** [comment]
Setting overdraw factor to 1 - 1.30 appears to eliminate this issue on my end. The blank tiles appear between 1.40 - 2.

Am i imagining it or does overdraw factor affect rendering speed in general? It seems to load tiles when zooming faster at 1 than 2, but i might be wrong. In any case, the white squares are gone with that.

**Comment by dennisguse** [comment]
For me, reducing overdraw factor seems to reduce the issue - everytime I also purged the cache, but there are still tiles that are reliably not loaded (or at least have a higher tendency).

**Comment by pstorch** [comment]
@dennisguse what is the best setting for you so far?

**Comment by dennisguse** [comment]
1.0

**Comment by pstorch** [comment]
Interesting, the lowest value. Does it mean no overdrawing? The documentation is saying anything about this value.

**Comment by pstorch** [comment]
@dennisguse can you try to run the mapsforge samples on your device and look for blank tiles?

**Comment by pstorch** [comment]
@dennisguse I myself don't get the mapsforge samples to build. Another app to compare would be FitoTrack, it uses mapsforge as well.

**Comment by dennisguse** [comment]
@pstorch I also had trouble - check that compileOnly points to your android.jar 

A quick test yesterday was working nicely using berlin.map

**Comment by pstorch** [comment]
I've just managed to run the mapsforge samples and they show the same TileCache capacity.
For a quick test I've change the code in OSMDashboard to double the TileCache capacity.

Can you @dennisguse and @crankc test this nightly build together with various overdrawFactors?

**Comment by crankc** [comment]
I tested it, and i no longer get blank tiles on higher overdraw settings. I tried 1.0, 1.1, 1.6 and 2.0. No blank tiles anywhere.

**Comment by pstorch** [comment]
That was fast 😀
Thanks. So it looks like we found the cause. The TileCache was to little.
I'll make it configurable and a release shortly.

**Comment by dennisguse** [comment]
@pstorch can confirm as well. Just used the nightly and it works nicely :)

Well done!

**Comment by pstorch** [comment]
fixed, release is on its way
