### ISSUE TITLE
OSM Dashboard not offered in OpenTracks

### ISSUE THREAD

**Issue by Buntbart** [OpenTracksApp/OSMDashboard#164]
OSMDashboard is not offered to me in the menu when I tap on the map icon in OpenTracks. Only other apps that can process GPX files appear there, such as OsmAnd or c:geo, but neither OSMDashboard nor OSMDashboard (offline).
I am using the latest versions of F-Droid on LineageOS 18.1 (Android 11) without Google services installed.

**Comment by dennisguse** [comment]
Settings -> User Interface (2nd) -> Select "show on map" behavior (last): is set to GPX.
Adjust it your needs.

**Comment by Buntbart** [comment]
Found it, thank you!
