### ISSUE TITLE
Zoomlevel enhancements

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OSMDashboard#17]
While using OSMDashboard I found some smaller things regarding the zoom level:

* limit minimal zoom to 10m: usually GPS is not that precise
* limit initial zoom level to 100m:
 I opened a newly started track ( I guess it just had one trackpoint) and the initial zoom level was less than 1m.
  I just wanted to get a quick overview of the landscape.
* while manual zooming (via pinch gesture), there is always a follow-up animation that seems to jump to the closest zoom level.
  Could we either make then zoom continuous or limit the initial zoom animation to just use zoom levels?

**Comment by pstorch** [comment]
I've moved the continuous zoom feature request to a separate issue, because this seems a bit tricky.
