### ISSUE TITLE
Continuous zoom

### ISSUE THREAD

**Issue by pstorch** [OpenTracksApp/OSMDashboard#18]
Part 2 of #17 

- while manual zooming (via pinch gesture), there is always a follow-up animation that seems to jump to the closest zoom level.
Could we either make then zoom continuous or limit the initial zoom animation to just use zoom levels?

**Comment by pstorch** [comment]
As discussed here https://github.com/mapsforge/mapsforge/issues/75, there is another mapsforge library [VTM](https://github.com/mapsforge/vtm) which renders the vector tiles with OpenGL and allows continuous zooming.

**Comment by dennisguse** [comment]
Okay - that sounds like a lot of effort. And I am worried about the performance impact on low-end devices (I got a Moto xt1039; 1GB).
But using vectors would have the advantage of making the map actually configurable (showing only the things you want to see).

Long story short: I don't know.
For me, there are bigger things to fry in OpenTracks first...

**Comment by pstorch** [comment]
fixed by #321
