### ISSUE TITLE
colour speed on tracks

### ISSUE THREAD

**Issue by pstorch** [OpenTracksApp/OSMDashboard#205]
From Diskussion https://github.com/OpenTracksApp/OpenTracks/discussions/1505

It will be good to be able to see one's differentiated speed on the map

green=faster
yellow =medium
red=slower

Medium is avg speed/pace
and if it varies more than, for example, ±10%, it will be red or green, the % can be configurable

**Comment by pstorch** [comment]
@dizmoduck there is a working draft in the current nightly build. Can you give it a try?

**Comment by dizmoduck** [comment]
Looking good, just like I have seen in other tracking app.

But there are some gaps in the tracks, I have checked with several tracks and it is the same.

If the % could be so that it could be adjusted, it will be nice 

![Screenshot_20230324-074605](https://user-images.githubusercontent.com/8668926/227445902-0be7c37a-c46c-497e-b70c-0e8d26d7a02a.png)

**Comment by pstorch** [comment]
> But there are some gaps in the tracks, I have checked with several tracks and it is the same.

That might depend on OpenTracks. If the GPS reception is bad. You can export it to GPX and look into the file. If you see more than one `<trkseg>` element, than this is the case.

@dennisguse please correct me if I'm wrong.

> If the % could be so that it could be adjusted, it will be nice

Do you want hard colors (only red, yellow and green)? At the moment I have shades of red and green.

**Comment by dennisguse** [comment]
@pstorch that is correct: gaps in the track are a result of bad GPS reception and "Max distance" between points in OpenTracks settings.

**Comment by dizmoduck** [comment]
With single color there is no gaps, but you are right about multiple <trkseg> in the gpx file

The colors are OK I was wondering if it was possible to adjust the variation from the avg. moving speed/pace, but it was an option that I have not seen before and maybe that's not relevant 

![Screenshot_20230324-083700](https://user-images.githubusercontent.com/8668926/227457919-bfb2462a-6f48-4e44-aba2-62b685695c1c.png)
![Screenshot_20230324-083527](https://user-images.githubusercontent.com/8668926/227457938-b6323ce2-6adb-4879-af5c-378e7e717c72.png)

**Comment by pstorch** [comment]
> With single color there is no gaps, but you are right about multiple "trkseg" in the gpx file

Hmm ok, then I have to look into that, too.

**Comment by dizmoduck** [comment]
Humm i can't upload a gpx file you can play with

**Comment by pstorch** [comment]
As .zip maybe?

**Comment by dizmoduck** [comment]
That help thanks 

I appreciate your work on this app, there is not far from an idea until it is executed 😁

[2023-03-23_10_19_09.779_2023-03-23T10_19+01.zip](https://github.com/OpenTracksApp/OSMDashboard/files/11060615/2023-03-23_10_19_09.779_2023-03-23T10_19%2B01.zip)

**Comment by pstorch** [comment]
Thanks for the file. I found the cause for the gaps. They were caused by trackpoints with speed = 0. I didn't handle that properly. I need to draw a red line then.
Can be tested in the next nightly build.
I also had to disable the coloring for currently recording tracks.

**Comment by dizmoduck** [comment]
I will test it sat when I go out for a walk

Could be a bug because for all I know I was moving or had a short stop to orientate which way to go?
