### ISSUE TITLE
configured buttom line on dashboard

### ISSUE THREAD

**Issue by dizmoduck** [OpenTracksApp/OSMDashboard#206]
The data that comes over the dachboard from tracking at the bottom of the map. It would be good if it could be configured, for example I would prefer moving time, pace and distance. 

![Screenshot_20230323-234655](https://user-images.githubusercontent.com/8668926/227387806-623ea494-30e4-4e73-9932-824e05532d89.png)
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pstorch** [comment]
A first rough implementation of this will be available in the next nightly build.
I'm not finally happy with the layout (ordering and labels). Also the imperial units are not supported yet.

@dennisguse now we need more of the units and conversation logic from OpenTracks also in the Dashboard. Is it worth thinking about a common library? Or better copy & pasting where needed and stay independent?

**Comment by dennisguse** [comment]
@pstorch the answer can only be yes. ;)
What functionality do we need? 
And we may also be able to transfer the data from OpenTracks?

**Comment by dizmoduck** [comment]
Looking good
![Uploading Screenshot_20230402-234205.png…]()

**Comment by dizmoduck** [comment]
Looking good! 

![Screenshot_20230402-234205](https://user-images.githubusercontent.com/8668926/229380636-5cd66ca6-381a-4dbf-9a29-be7f44eb2508.png)

**Comment by pstorch** [comment]
> @pstorch the answer can only be yes. ;) What functionality do we need? And we may also be able to transfer the data from OpenTracks?

Transfer from OpenTracks is also an idea. For example the setting if the user prefers Imperial over Metric Units.
The speed is currently provided as m/s and the dashboard needs to convert it to km/h, mi/h and to pace in min/km and min/mi. Also elevation gain from m to ft.
All in all not that much. Maybe duplication is not really an issue. At least less then introduceing compile time coupling between the two projects.

**Comment by dennisguse** [comment]
Them it is likely only the Speed and Distance classes IIRC.
If we use the same package structure it wouldn't be that confusing?

Transferring the unit is okay, but will be a string(?) as it is more then one option nowadays.
The Unit class might be needed as well.
Transferring the unit via the Tracks url would work?

**Comment by dizmoduck** [comment]
There is a bug, don't know if it came with this update of the "configured button line on the dashboard". 

Is show when you are viewing the trail your are recording on the dashboard every time it's updating 

![Screenshot_20230405-115000](https://user-images.githubusercontent.com/8668926/230210537-3cd551f5-bc70-4040-b368-15e5e86c6866.png)

**Comment by pstorch** [comment]
Nice 😃
Thanks for reporting, I'll have a look.

**Comment by pstorch** [comment]
@dizmoduck it's fixed now. If you haven't found any other issue, then I thinks it's ready for a release.

**Comment by dizmoduck** [comment]
sound great, I'll test it this afternoon (CET time)

**Comment by dizmoduck** [comment]
Another little funny error 

Shout category not be first, when I mark mulit tracking it shuffle around

![Screenshot_20230406-181715](https://user-images.githubusercontent.com/8668926/230439310-7b0f64aa-7af5-44e3-a41d-e148c0992c04.png)

**Comment by dennisguse** [comment]
@pstorch why not just say "categories: multiple"?

**Comment by pstorch** [comment]
I totally forgot how the Dashboard handles it, but it should already be stated as "mixed":
https://github.com/OpenTracksApp/OSMDashboard/blob/main/src/main/java/de/storchp/opentracks/osmplugin/utils/TrackStatistics.java#L45

**Comment by dizmoduck** [comment]
If they are defeat it will say "mixed" and if they are the same it will say with one. 

The order isn't that important as long it will start with the categories

**Comment by pstorch** [comment]
Ok, makes sense. I'll order it so that the category goes first if selected.
