### ISSUE TITLE
Filter compass values

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OSMDashboard#21]
The compass presentation is kind of jumpy as well as jittery.
Filtering the data might reduce this effect.

One idea would be to use:
https://stackoverflow.com/questions/7092355/smoothing-the-values-of-the-compass-on-android-devices

**Comment by pstorch** [comment]
@dennisguse can you check if this reduces the jumpyness on your device?

**Comment by dennisguse** [comment]
Works like charm.
