### ISSUE TITLE
OSM Dashboard (Nightly) crashed

### ISSUE THREAD

**Issue by dizmoduck** [OpenTracksApp/OSMDashboard#218]
when I select several tracks at the same time as displaying a recording track, the open dashboard crashes every time it's update the tracking track 

### App information
* ID: de.storchp.opentracks.osmplugin.nightly
* Version: 704 2.18.0-704
* Build flavor: full

### Device information
* Brand: Blackview
* Device: BV8000Pro
* Model: BV8000Pro
* Id: O00623
* Product: BV8000Pro

### Firmware
* SDK: 26
* Release: 8.0.0
* Incremental: 1527662266

### Cause of error
```java
Exception in thread "LayerManager": java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at org.mapsforge.map.layer.GroupLayer.draw(GroupLayer.java:42)
	at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:95)
	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)

```

**Comment by pstorch** [comment]
Thanks for reporting. 
Interesting, but I couldn't not yet reproduce it. Let me think, what I can do here.

**Comment by dizmoduck** [comment]
The way I do it 
1: start recording 
2: selected 4 tracks include the recording one
3: choose show on map
4: it's important that you start moving the phone, then when it's update the route on the map the dashboard crashes on my mobile

**Comment by pstorch** [comment]
That's what I tried. But couldn't cause the crash. I'm still thinking about it. Maybe the existing tracks are very big and need longer to draw. So that the first update from the new track comes while the old tracks are still being drawn.
Can you test with just two?

**Comment by pstorch** [comment]
I'm not sure if it helps, but I tried something. As I still cannot reproduce it, it would be nice if you can test the next nightly build.

**Comment by dizmoduck** [comment]
I think i might got it now! 
I forgot to the app clean cache after new update 

This time after I updated with the new Nightly build I remember to clean the app cache under android settings -> app info

It work with 4 tracks + the one that is recording 

The combined gpx files are around 1.5Mb

Btw you can't see the dashboard version № in the app under "About"

**Comment by pstorch** [comment]
Thanks for testing again. Sounds good.
Also good idea to add the version number in about. I'll add it.

**Comment by dizmoduck** [comment]
Just happy to help with an open source project that prioritizes privately, it's also nice that it's not far from idea to action.

If I get new ideas, I'll will suggests them😁

Now we just need to improve the static and other ideas in OpenTrackers😁
