### ISSUE TITLE
Remove module?

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OSMDashboard#22]
OSMDashboard is configured as a module, which is called 'app'.
However, as it is the only project in the repository we can also remove the module, right?

**Comment by pstorch** [comment]
Again something I did because I always do it like that or because Android Studio did set it up like this and I don't know why.
How does it look without a module, what is the impact and is it worth the effort?

**Comment by dennisguse** [comment]
Then it looks like OpenTracks - basically everything moves one folder up.
Also then only one gradle file is necessary.
So, no real advantage just less clutter :)

**Comment by pstorch** [comment]
Then please go ahead, if you like 😉
