### ISSUE TITLE
Use multiple offline map files in parallel

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OSMDashboard#24]
I can only select one map file to be used for offline rendering.
For example, Germany is usually split by federal country (one map file per federal country).
If I am on a trip over crossing country borders (e.g., Berlin and Brandenburg), then I only get the map for one of them.
So, I cannot see the whole map...

Mapnik works as desired.

**Comment by pstorch** [comment]
Good idea

**Comment by dennisguse** [comment]
That was really quick!
Thanks!
