### ISSUE TITLE
can't get past the welcome screen

### ISSUE THREAD

**Issue by nestoris** [OpenTracksApp/OSMDashboard#241]
Can't get past the welcome screen, it won't scroll down.
Mi a2 Lite, Lineage OS.
![Screenshot_20230624-034238_OSM_Dashboard](https://github.com/OpenTracksApp/OSMDashboard/assets/26491673/910b2b6c-ebfc-4af7-baec-f850e96a45b7)

**Comment by pstorch** [comment]
Thanks for reporting. I've added scrollbars to the main screen.

Just in case there is a misunderstanding: you don't see much more here. The version number is the last thing on that screen. To view tracks you have to go to OpenTracks, select a track there and use the "Show on map" button there to open the Dashboard with the map view.
