### ISSUE TITLE
Feature idea: Explorer Function

### ISSUE THREAD

**Issue by khao-soi** [OpenTracksApp/OSMDashboard#244]
I kinda like the explorer function of [Wander.earth](https://wandrer.earth/) but it is bound to Strava. It basically just aggregates all your tracks and shows them on a map to visualize where you went over time and where not. It has additional features like colour-code new explored ways / streets and rankings etc., but that's not the fun part.

I would like to have something similiar in OSMDashboard: A map that just shows all of your tracks ever recorded (with markers), what areas you have already discovered and where there is "fog" on the map for you.

We basically already have that functionality by selecting all of your tracks in OpenTracks and show them on the dashboard, but it's kind of unpractical as you would always have to select each track every time you wanna have that view. Also for this case it is not neccessary to use different colours for each track.

Basic functionality would be:
- A button in OpenTracks to open Explorer View
- Show all tracks with its marker in one colour in OSMDashboard (zoom accordingly)

Nice to have (later on):
- (Optionally) Highlight newly discovered tracks in single track view in OSMDashboard
- Show newly explored track kilometers by interval (week, month) 

What do you think?

**Comment by pstorch** [comment]
Interesting use case. Paint all tracks in one color would be the easy part. Could be a configurable option right now.

But I guess the explore view would need to aggregate the tracks somehow. Merge the trackpoint if they are close enough. And calculate the "fog" somehow.

**Comment by khao-soi** [comment]
The "fog" was more figuratively speaking for undiscovered areas, not the warcraft map way ;) So theres nothing calcuate / show here.

An aggregation of overlapping parts of tracks would be nice tho.

**Comment by khao-soi** [comment]
@pstorch I was thinking about this a little. The best scenario would be to align the tracks to the existing ways of OpenStreetMap. But I don't think we have that data in OSMDashboard, since it _just_ uses the bitmap tiles.

My first idea was to align the points to a geographical resulution of 4 decimal places via `round`. A quick test showed, that it kinda works in some cases, but overall its not really satisfying.

Another approach would be to follow one track of many, for each track point collect close by track points of other tracks and aggregate them to a common center. I haven't tried that (yet).

I don't have too much experience with these kind of things. Do you know of any established way to solve this kind of problem?

**Comment by khao-soi** [comment]
> But I don't think we have that data in OSMDashboard

Or do we? Is there some like the `TileDownloadLayer` but to get the ways of a `IMapViewPosition`?

**Comment by pstorch** [comment]
> > But I don't think we have that data in OSMDashboard
> 
> Or do we? Is there some like the `TileDownloadLayer` but to get the ways of a `IMapViewPosition`?

I don't know, would need to dig into the mapsforge api. But the online map uses prerendered tiles.

**Comment by khao-soi** [comment]
Could be `readMapData` of `MultiMapDataStore`: https://github.com/mapsforge/mapsforge/blob/master/docs/MapDataStore.md

**Comment by pstorch** [comment]
Other challenge: I guess OSMDashboard would then need a database, too. To store all previous (consolidated) tracks, to recognize new areas, when called with a new track.

**Comment by khao-soi** [comment]
Right. Obviously this feature has many degrees of complexity. From straight forward just showing all existing tracks in one color to having tracks aligned with OSM ways and new area detection.

What do you think would be a good first approach? If you consider to add it at all.

If so, we might break it down into 2-3 tasks that could be added in succession.

**Comment by pstorch** [comment]
If coloring all tracks in one color would be useful, that could be an easy first step.
Regarding the next steps I need to think a bit longer. I don't want to implement too much complexity.

**Comment by khao-soi** [comment]
Yes, that would be a nice start. Not sure wether the markers are useful in that view or not, probably the latter.

I might try write a simple function to group close by `TrackPoints` of different `Tracks` arround a common center, to sanatize the view a little.

**Comment by pstorch** [comment]
@khao-soi I've added an option to color the tracks all in the same unicolor. It's available in the nightly, in case you want to try it.

**Comment by khao-soi** [comment]
Aggregation of `TrackPoints` kinda works and the view looks cleaner. I need to play aroud with thresholds a little. But there are two downsides:
- The function has a complexity of O(n²) - I have like 25 tracks (500-2500 points) and it already takes 2 seconds or something to load (too long)
- Therefore `sphericalDistance()` isn't an option and I have to use `distance()` function which of course a varying geographical accuracy.

I might implent an R-tree function. Whew, not exactly trivial.

**Comment by pstorch** [comment]
Just stumbled upon this:
https://bonn.social/@martin_ueding/111381563663989220

**Comment by pstorch** [comment]
Not in scope of OSMDashboard, there are better tools around which already implements this
