### ISSUE TITLE
API Map Refresh Rate Settings

### ISSUE THREAD

**Issue by DeathfireD** [OpenTracksApp/OSMDashboard#252]
I was on a hike today for the first time using OpenTracks and OSM Dashboard and noticed that OSM Dashboard does not show progress in real time. It seems to refresh every minute or so. When the map finally does update, the line indicating your path does not actually contain the actual path taken. Sometimes it's just a streight line from the last point that it refreshed at. Can you give some clarification on how often OSM refreshes at when using the API? Also, while on the subject, it would be nice to have the ability adjust how often it pulls track date and refreshes the map to show your progress. I'd like it to display my path more often for some hikes and less often for others...but I'd still like the path I took to be accurate, not a straight line lol.

**Comment by pstorch** [comment]
OSMDashboard doesn't pull new data from OpenTracks, but OpenTracks pushes updates to OSMDashboard. 
There might be several settings in OpenTracks and OSMDashboard influencing your observation. 
There is a track smoothing setting in OSMDashboard which reduces the number of drawn trackpoints. Set it to 0 to turn it of.
![Screenshot_20230712_124809_OSM Dashboard (Nightly)](https://github.com/OpenTracksApp/OSMDashboard/assets/5598124/7fcfd1bd-5d50-4436-8400-d66ffc0988bf)

Then there are the GPS settings in OpenTracks which have an influence on how many and when new track points are recorded. 

![Screenshot_20230712_125210_OpenTracks (Nightly)](https://github.com/OpenTracksApp/OSMDashboard/assets/5598124/0e76973a-b28c-40d3-9c5e-7ad9b1ac5780)


Try playing around with these settings.

**Comment by DeathfireD** [comment]
@pstorch Thanks! I'll mess around with the settings and see if that makes a difference!

**Comment by pstorch** [comment]
@DeathfireD any success?
