### ISSUE TITLE
A Display Bug

### ISSUE THREAD

**Issue by franklinbill** [OpenTracksApp/OSMDashboard#26]
Dear developer
In the process of using, I found a bug in layout / display. As shown in the figure, there is an overlap between the top text title and the text of the home page, which may be an adaptation problem.
App version is 1.5.0, my mobile phone is Google nexus 6, screen resolution setting is 1440 * 2560, font size is the largest, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
![image](https://user-images.githubusercontent.com/18572115/79122674-e8c03d80-7dca-11ea-9e0f-60ae4f617745.png)

**Comment by pstorch** [comment]
Thanks for reporting this issue. I've never changed my font size, so I've never seen this.
But I can reproduce and will have a look.

**Comment by franklinbill** [comment]
Thank you！

**Comment by pstorch** [comment]
Was easy to fix, will come with next release

**Comment by dennisguse** [comment]
@pstorch FYI: https://arxiv.org/pdf/2205.13945.pdf
Page 12; search for OpenTracks ;)

**Comment by pstorch** [comment]
@dennisguse oh, where does this come from?

**Comment by dennisguse** [comment]
Every now and then I check scholar.google.com as some people actually use OpenTracks for science :)
