### ISSUE TITLE
Incorrect display in OSM Dashboard

### ISSUE THREAD

**Issue by Geier0815** [OpenTracksApp/OSMDashboard#269]
**Describe the bug**
If I open the track with the cardsymbol, there will be a long blue line shown with an arrow at it's end. On some tracks there is under the arrow is a little square shown at others the line starts at this square. This little square is the map. I have to zoom in heavily and then I can see the track I was ridden.
The last track that will be shown correct is from the 18th of june. After that I had a break until 13th of august and this is the first track that shows this error.
The only thing that has changed, beside updates of opentracks and osmdashboard offline, is that I use a MI5 Band for the heart rate since then.
Changing the format of auto exported data to gpx does not make any difference

**To Reproduce**
1. Open a track
2. Click on the little card symbol

If applicable:
![Fehler-Opentrack-2023-08-13](https://github.com/OpenTracksApp/OpenTracks/assets/143877068/9e969049-3e26-4d02-860b-1173678572a6)

**Technical information**
 - Device: HMD Global Nokia 4.2      Modell:TA-1157
 - OS: Android One 11
 - OpenTracks version: v4.8.1/v4.8.1 Version Code: 5366

**Comment by dennisguse** [comment]
@pstorch which brings up the question: what changed in OpenTracks?

@Geier0815 could you export the track as a CSV?
It represents the internal data as close as possible: opentracks@dennisguse.de

**Comment by pstorch** [comment]
@dennisguse I can send it to you as well

I've implemented to ignore the 0,0 trackpoints. It will be available in the next nightly.
