### ISSUE TITLE
Support for Android 13's monochrome launcher icons

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OSMDashboard#279]
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

OpenTracks implementation: https://github.com/OpenTracksApp/OpenTracks/blob/aae1a4d65d9df154cce8e5d4500c550f34da8d8f/src/main/AndroidManifest.xml#L74

PS/ I was slightly confused by the rendered icons and that the lines are part of the background...

**Comment by pstorch** [comment]
I just wanted to comment that I already did this, but I checked again and it was in a different app. 😉

I'll do it here, too.

**Comment by dennisguse** [comment]
PPS/ I was also confused by all the PNGs (still) floating around...

**Comment by dennisguse** [comment]
Looks great :D
