### ISSUE TITLE
The menu "Map download" doesn't exist in the "offline" version

### ISSUE THREAD

**Issue by nach0** [OpenTracksApp/OSMDashboard#282]
I just downloaded OSM Dashboard (Offline) from F-Droid (latest version, 3.1.0 (40)), and upon launching the app the welcome screen states:

> Offline maps can be downloaded via the menu Map download 

However I cannot find the menu "Map download" anywhere in the Settings nor anywhere else in the app. Am I blind or does this menu not exist?

**Comment by pstorch** [comment]
Sorry, I recently moved it into the setting screen.
I need to update the description.

**Comment by nach0** [comment]
Thanks for your reply, however I cannot find it in the Settings screen. Is it there in version 3.1.0 (40) or was it maybe gone by mistake?

**Comment by pstorch** [comment]
It's here:

![Screenshot_20231016_215404_OSM Dashboard](https://github.com/OpenTracksApp/OSMDashboard/assets/5598124/8bd17ad7-5043-4a83-a15e-86158655c358)

**Comment by nach0** [comment]
That's weird. It's not there for me: Version, 3.1.0 (40) from F-Droid
![Screenshot_20231016-215707_OSM Dashboard (Offline)](https://github.com/OpenTracksApp/OSMDashboard/assets/1169440/5c7a6e43-234f-40bc-92f3-b70a3982f2cf)

To add more information: I've been using OSM Dashboard (the online version) for more than a year, and just yesterday I decided to download the Offline version and give it a try. I currently have both apps installed, but the screenshot is from OSM Dashboard (Offline). I don't know if having both apps installed could influence on this...

**Comment by pstorch** [comment]
Ah, you're talking about the offline version. Yes, the offline version doesn't have internet permission (offline), so it can't offer to download maps from within the app. You need to download them separately via the Browser and afterwards point the "Map directory" to where you have downloaded them. 

Ok, I need to adjust the description for the offline version to make this clear.

**Comment by contrapunctus-1** [comment]
@pstorch Most users would expect an "offline dashboard" to mean "something that can download and display offline maps". Not being able to download offline maps from within the offline dashboard is not the smoothest UX, and it's surprising and confusing (as a user) to find a download manager for _offline_ maps in the _online_ dashboard...

**Comment by pstorch** [comment]
@contrapunctus-1 thanks for your feedback. I see your point. What would be a better name for this app version "without internet permission"?
