### ISSUE TITLE
Location access needed?

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OSMDashboard#3]
As the dashboard only shows data provided by OpenTracks, location access is not necessary, or?
Even if the user wants to re-center the map, OSMDashboard could just jump to last provided point.

**Comment by pstorch** [comment]
It's already removed ;)

**Comment by dennisguse** [comment]
Faster than the speed of light...

**Comment by dennisguse** [comment]
Permission `ACCESS_FINE_LOCATION` is still in place...

**Comment by dennisguse** [comment]
Forget it - I was too blind to do a git pull on the correct branch...
