### ISSUE TITLE
Can't add multiple offline maps

### ISSUE THREAD

**Issue by Vandekin** [OpenTracksApp/OSMDashboard#312]
If this issue is not linked to OSMDashboard, feel free to tell me and I'll search help elsewhere.

I use the offline version of OSMDashboard and I downloaded multiple maps on https://www.freizeitkarte-osm.de.
The first one was the map the Croatian region because I swam there in September and it worked as expected. This weekend, I went to swim in a lake in France (near Chambery) and I recorded my trace.

I downloaded the map of the concerned region. It is detected by OSMD but not displayed in the viewer. I tried with two other maps (an other region of France adjacent to the previous one and an the Austrian region that is adjacent to the Croatian one). I have the same behavior, the maps are detected in the setting of OSMD (screenshot attached) but not displayed in the viewer (screenshot attached).

I tried to only select the faulty maps (so unselect the Croatian one) and I got the error pop up : "You have no offline map configured yet".

Map selection screenshot :
![image](https://github.com/OpenTracksApp/OSMDashboard/assets/46026245/f0e94c1d-2954-4b07-853a-d3bbce3da5f5)

Map in viewer with the previous screenshot parameters:
![image](https://github.com/OpenTracksApp/OSMDashboard/assets/46026245/17333692-bc8b-4c8f-a698-ded2e46e0231)

Error when I deselect the Croatian map :
![image](https://github.com/OpenTracksApp/OSMDashboard/assets/46026245/34d642b1-6896-4b78-bc29-97913cf02dba)

**Comment by pstorch** [comment]
Are the maps all in the same directory and did you choose that directory in OSMD?

**Comment by Vandekin** [comment]
Yes, all in the same directory and the directory was choose in OSMD.

**Comment by pstorch** [comment]
I'm thinking about the + sign in the file names. Can you check if the files have the same if you look in the directory with a file manager?

**Comment by Vandekin** [comment]
They all have the + sign even the Croatian one (Freizeitkarte_HRV+.map).

![Screenshot_20231211-191529_Files](https://github.com/OpenTracksApp/OSMDashboard/assets/46026245/cfde4491-f16c-41e8-bc53-1a5cdcd04169)

**Comment by pstorch** [comment]
The directory from the file manager says "maps", but the chosen directory in OSMD says "primaryMaps".

**Comment by pstorch** [comment]
Hmm, I can use all 4 files. Can you try each one individually? Maybe one is corrupt.

**Comment by Vandekin** [comment]
I don't know why, but after testing them one at a time, everything works fine now ¯\_(ツ)_/¯

Thanks for your help 😄
