### ISSUE TITLE
Download offline maps from with OSMDashboard?

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OSMDashboard#32]
Especially for less tech savy users, it would probably great to download offline maps from within OSMDashboard.
Also, I have the feeling that the initial setup of offline maps is rather complicated (not really intuitive).

Could we improve this somehow?

**Comment by pstorch** [comment]
Yes, that would be a nice feature.
But not easy to implement. I remember a long discussion I was involved here: https://github.com/cgeo/cgeo/issues/6072

tl;dr:
- Only few Map providers allow direct download from within your app (OK, one would be enough for us)
- some map providers offer download links which could be captured by app intents. But these are app specific and must me aligned with each provider to have it included on their download page. That's what I've seen for Locus Maps and Ocrux. We could "listen" on one of those URIs, but it doesn't feel right. Same has to be done for themes.


I've seen a new approach from c:geo to only download from one mapsforge mirror, which allowed downloading from within the app and doesn't need an extra theme. Maybe that's an option for the OSM Dashboard, too.

**Comment by dennisguse** [comment]
Would it be possible to show a list of potential sources (i.e., links) and if the user chooses a source, a webview could be opened.
The we could limit the navigational freedom (just go to url-subpaths) and wait for download events?
Then we would have the selected map url and could download it within OSMDashboard.

PS: Don't know exactly if this would work :)

**Comment by pstorch** [comment]
That could be done with the basic mapsforge maps. Other map providers require proper themes and then we would need to direct the user to the proper themes according to the maps provider.

**Comment by pstorch** [comment]
Not pretty, but you could move around in the directories and choose a map. Then we can intercept the map URI and download in the background.
![Screenshot_20200430-214758_OpenTracks_-_OSM_Dashboard](https://user-images.githubusercontent.com/5598124/80753042-e5e47d00-8b2c-11ea-9661-0e6d25e245c1.png)


Another question is where to put it?
- use the "Offline Map Directory" which we have right now: then this needs to be writable (which I'm not sure if that is a good idea) and chosen prior to download
- use the internal app specific storage, but then we have two directories where to look for .map files
- we could rename the "Offline Map Directory" to "External Map Directory" to make it clear that there is a distinction between maps shared with some other apps (external) or maps which are downloaded within the dashboard.

**Comment by dennisguse** [comment]
Mhh. 
I thought we use the offline map directory, but you are right.
I still like the idea to share the files between apps - so we could ask for permanent permission for one folder.

**Comment by pstorch** [comment]
After thinking a while about it, it might be better to request a writable Offline Map Directory than confusing them with two different ones.

**Comment by pstorch** [comment]
I have a basic working version at https://github.com/OpenTracksApp/OSMDashboard/tree/download_mapsforge_maps

But while testing the download, I see that the solution to dynamically add the .map files which can be found in the offline map directory to the menu is not a good solution. It takes longer and longer and there is no possibility to delete a map file.

I think I should move them out of the menu into a mapchooser list activity.

**Comment by pstorch** [comment]
I've pushed the first working version, I'll open another ticket to rework the maps menu.
