### ISSUE TITLE
online maps are used without consent, leaking location

### ISSUE THREAD

**Issue by gdt** [OpenTracksApp/OSMDashboard#33]
The app loads online map tiles when first started, at least if clicked form Open Tracks.  It would be nice to have a wizard that asks the user to configure offline or grant permission to load online maps, explaining that locations are sent in the API, with a link to the privacy policy of the tile servers and tile server CDN network.

(It's great that mapsforge support is there; it was easy to configure it for my existing mapsforge map.)

**Comment by pstorch** [comment]
The usage of the online map is explained in the app description. But not the detail, that this means leaking of the location to the map provider.
Asking for consent on first use would be more safe, yes.

Offering the user to dowload offline maps instead is related to #32

**Comment by gdt** [comment]
Thanks very much for listening and implementing this.   In  2.0.0, I see online consent unchecked and my mapsforge map still works fine.  Changing to mapnik i get a popup with privacy policy - so this looks totally great!

**Comment by pstorch** [comment]
Thanks for testing and the feedback.
