### ISSUE TITLE
Hide OSMDashboard icon

### ISSUE THREAD

**Issue by gabsoftware** [OpenTracksApp/OSMDashboard#34]
If OSMDashboard is just a plugin for OpenTracks, you might as well hide the icon from the app drawer.

**Comment by dennisguse** [comment]
The icon just opens the start page that describes how to setup offline maps.

**Comment by pstorch** [comment]
I'm also in favour of keeping the icon.

**Comment by pstorch** [comment]
@gabsoftware is it ok for you to close the issue?

**Comment by gabsoftware** [comment]
Closed as requested.
