### ISSUE TITLE
Trail names

### ISSUE THREAD

**Issue by downtownallday** [OpenTracksApp/OSMDashboard#350]
I use OpenTracks to record my hikes in the mountains and prior to version 4, maps showed trail names. Now they're missing. Roads and mountain peaks have labels, but not trails. Thanks.

Btw, the new map display is great!

**Comment by downtownallday** [comment]
Additional detail: I'm using offline maps (downloaded from ftp-stud.hs-esslingen.de - america/us/new-hampshire.map).

**Comment by pstorch** [comment]
Hmm, probably some style / rendertheme differences between mapsforge and vtm. I'll have a look.

**Comment by pstorch** [comment]
@downtownallday I found some adjustments, that could help here. Would be cool, if you could test the next nightly build.

**Comment by downtownallday** [comment]
Works! I see labels for trails and other labels still present. There are labels for viewpoints as well. Thanks!
