### ISSUE TITLE
It crushed 

### ISSUE THREAD

**Issue by Just-Explode** [OpenTracksApp/OSMDashboard#357]
Maybe I'm having too many of traces?

**Comment by Just-Explode** [comment]
Ah damn it, i can't be really opening a issue just now...

**Comment by pstorch** [comment]
Thanks for reporting, but without any more details, I think I can't do much.

**Comment by Just-Explode** [comment]
I'm really sorry. I shouldn't be posting this yet. I haven't got time to do proper research, yet I accidentally opened an issue without the logfile :v

**Comment by pstorch** [comment]
No problem, just add it, when you have it.
