### ISSUE TITLE
Settings option: keep screen on

### ISSUE THREAD

**Issue by rgmf** [OpenTracksApp/OSMDashboard#36]
This option would be great like in OpenTracks because if you use this option in OpenTracks and you open OSMDashboard the screen is going off.

**Comment by pstorch** [comment]
Makes sense while recording. 
@dennisguse should this setting be forwarded from OpenTracks?

**Comment by dennisguse** [comment]
That's  a pretty good idea.
How can we transfer this information and do we need to handle settings updates?

Any suggestions?
I have no clue :)

**Comment by pstorch** [comment]
I would try to use the Intent Extras. So we have the most current setting at every call of the Dashboard.

**Comment by dennisguse** [comment]
@pstorch excellent :)
That's a pretty simple, good idea!

**Comment by pstorch** [comment]
I'll look at it this weekend.
