### ISSUE TITLE
Confusing loading state in Battery Saver

### ISSUE THREAD

**Issue by graciouselectric** [OpenTracksApp/OSMDashboard#369]
Dear developer,

I noticed that when I enable Battery Saver on Android 8.1, the indeterminate `ProgressBar`s in the app are not properly shown. This is a known problem in Android API level <28, see e.g. [this StackOverflow question](https://stackoverflow.com/questions/35221706/progressbar-disappears-in-battery-saver-mode-android-5-x). Battery Saver disables animations, also on progress bars on these versions. This is quite confusing because the loading state is not properly represented. It is fixed in later Android versions, where progress bars do appear and animate.

Looking at the code, indeterminate progress bars are created here:

```
className='de.storchp.opentracks.osmplugin.DownloadActivity', lineNumber=57
className='de.storchp.opentracks.osmplugin.DownloadActivity', lineNumber=157
```

To fix this issue, one can check [ValueAnimator.areAnimatorsEnabled()](https://developer.android.com/reference/android/animation/ValueAnimator) and provide a different UI element, such as a text label, when animations are disabled.

I also recorded a video, showing the issue in practice:

https://github.com/OpenTracksApp/OSMDashboard/assets/165037835/ee2efef0-a312-4a37-be83-e3218ad514a0

**Comment by pstorch** [comment]
Thanks for reporting. I've never experienced it, so far.
Replacing the progress bar with a text in case of disabled animations feels a bit awkward, but I'll think about it.

**Comment by pstorch** [comment]
@graciouselectric the download is changed in the current nightly version to use a Download Manager and the progress bar is not "indeterminate" anymore.
Can you test this version?

**Comment by dennisguse** [comment]
@pstorch works for me :)
