### ISSUE TITLE
Logo...

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OSMDashboard#37]
... we might need a new one.

I am trying to prepare some options.

**Comment by pstorch** [comment]
Do you have anything special in mind about the logo?

**Comment by dennisguse** [comment]
Not really: basically adding a dark gray background to the "arrow" that looks like a map.

**Comment by pstorch** [comment]
So the map not in small in front of the arrow, but as a big background?

**Comment by dennisguse** [comment]
@pstorch Yes - just my Inkscape skills prevent me from doing this :)

**Comment by dennisguse** [comment]
And wait: I mean not the map icon; I mean a black background (with two/three white lanes) and on top the arrow.

**Comment by pstorch** [comment]
I'm not sure, if I understand what you have in mind. Maybe something like this?

![image](https://user-images.githubusercontent.com/5598124/83919958-07fc9b00-a77c-11ea-885c-79b1ec62161f.png)

**Comment by dennisguse** [comment]
Something like that as an adaptive icon.

**Comment by pstorch** [comment]
<- Reading Android adaptive icon specification

**Comment by dennisguse** [comment]
https://github.com/OpenTracksApp/OpenTracks/issues/121 is related.
I have (hopefully) a fix for this issue (icon was too small and MIUI rendered it correctly).
For OSMDashboard, we would then only need to provide a second vector image as background.
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive?hl=en

A branch with the fixed logos is here: https://github.com/OpenTracksApp/OpenTracks/tree/logoSize%23121

Changes were not yet tested with MIUI.

**Comment by dennisguse** [comment]
Looks good!
