### ISSUE TITLE
Themes not loading from specified directory

### ISSUE THREAD

**Issue by dipyamanroy** [OpenTracksApp/OSMDashboard#381]
Downloaded the Dark Matter theme style from as found here, https://github.com/openmaptiles/dark-matter-gl-style. Placed it in a themes folder, however OSMDashboard did not recognize. I could not find an appropriate tutorial on how to add and change map themes. Any help would be appreciated.

**Comment by pstorch** [comment]
Unfortunately OSMDasboard only supports xml render themes as described here: https://github.com/mapsforge/vtm/blob/master/docs/Rendertheme.md

**Comment by dipyamanroy** [comment]
Thanks for responding so promptly. Is there a way to convert a respository with a theme (https://github.com/openmaptiles/dark-matter-gl-style) as I shared previously to the required format automatically? 

Being a layman, I may not have the necessary skills to make my own theme with the permissible format.

**Comment by pstorch** [comment]
I don't know any way to convert it. Maybe you can also ask in this repo, if they can provide the theme in other formats.

**Comment by dipyamanroy** [comment]
Alright. Do you know any themes (other than the default) that work on OSMDashboard that I can try out?

**Comment by pstorch** [comment]
I know that these two map sources offer their own themes:

 - [Freizeitkarte Android](https://www.freizeitkarte-osm.de/android/en/)
- [OpenAndroMaps](https://www.openandromaps.org/en)

Sometimes a theme only works properly with a specific type of map and vice versa.  That's why these two offer their own themes.

**Comment by dipyamanroy** [comment]
Much appreciated, will look into these. I'll close the issue. Thanks for all the help.
