### ISSUE TITLE
Show on map opens wrong app

### ISSUE THREAD

**Issue by wforumw** [OpenTracksApp/OSMDashboard#385]
Hi,
When I try to see my track on maps it opens with a wrong app, although I have installed OSM Dashboard for OpenTracks.
When I remove this (other) app I get 'no apps can perform this action. Is there a way to open it with the OSM Dashboard.

Kind Regards,

**Comment by dennisguse** [comment]
Please check the settings of OpenTracks. You may have selected KML or GPX. ![Screenshot_20240706-124909.png](https://github.com/OpenTracksApp/OSMDashboard/assets/2820825/49b0da7c-bcaa-41cb-a296-6f0858127d9a)
