### ISSUE TITLE
Better download UI/UX

### ISSUE THREAD

**Issue by contrapunctus-1** [OpenTracksApp/OSMDashboard#397]
The map download interface is functional but quite rough at the moment. Please look at the download manager in Organic Maps for inspiration.

1. If a user has offline maps selected, opens a track, and there's no map data for that area, offer to download the map for that area.
  Extracted to #418

3. Use a native UI (as opposed to the current webview) to list maps for download.
  Extracted to #417

4. Download resumption does not seem to be supported. This is necessary for downloading large map files, such as India (1.3G), over unstable connections.
   Extracted to #403

5. Notify the user when there are newer versions available for their downloaded maps. Ideally using a red dot to guide them to the updated maps, similar to Organic Maps.
  Extracted to #419 

Thanks.

**Comment by pstorch** [comment]
I've extracted all feature requests into their own issues to better handle and track them.
Closing this issue.
