### ISSUE TITLE
Sunsetting the offline version? 

### ISSUE THREAD

**Issue by pstorch** [OpenTracksApp/OSMDashboard#398]
I'm thinking about sunsetting the offline version. 
It's causing confusion, see #282, and the same behavior can be achieved by denying the online map consent.

**Comment by gdt** [comment]
I guess the real question is the paranoia level of the users.   I'm very sympathetic with high paranoia, but thinking about it:
  - if you actually care about location privacy, everything about opentracks is insignificant unless you are running a degoogled ROM
  - once you are running e.g. CalyxOS, you can deny internet permission in the firewall if you want
  - while the permissions model is very useful, the fundamental issue is that you should only run code from places that you trust to act in your interest
  - with no maps for the current location, it makes sense to show instead a "configure maps" button, and have that take you to a screen that says "There are two ways to get maps.  One is to fetch tiles as needed, which is easy to configure, uses data, and leaks your location.  The other is to once fetch a map for a large area and use it offline." or something and then have buttons "consent to fetching tiles (leaks location)" and "fetch map for offline use (large data use at time of downloading)" and have the lower one lead into the download.

and sure, keep settings for later and fancier users.   I've pretty much come around to thinking that the offline-only no-internet version isn't really nceessary.

**Comment by nutpantz** [comment]
Since switching to Android download manager which is 90% of the time bundled with mtp and other oem apps, you have pretty much now have a ton more info reported to Google when attempting to downloading maps from the online app. I would vote to keep the offline version, since there is no ui for the Android download manager you never know when it will decide to download something, i would rather never take the chance it might try, and if you disable Android download manager to protect privacy your app will crash since it's not there.(which is the only method of blocking without root)

**Comment by pstorch** [comment]
Thanks for your feedback. The offline version will be continued.

**Comment by dennisguse** [comment]
@nutpantz do you have some links for the described behavior?

**Comment by nutpantz** [comment]
Links? No Google does not accept bug reports for devices that are rooted or have firewalls. Most developers don't either.
There is no ui for the Android download manager. No way to cancel a download in que. Or even tell there is a download in que.
It's easily testable to stimulate.
Connect to a wifi router that has no internet and start a download. Then try to find if it's in que.
I've had downloads start a week later back before i just always disable download manager.
Now i see all the apps that crash with it disabled, even when i never ask them to download anything.

I'll look for links
https://developer.android.com/privacy-and-security/risks/unsafe-download-manager
