### ISSUE TITLE
Use download manager for offline map

### ISSUE THREAD

**Issue by pstorch** [OpenTracksApp/OSMDashboard#403]
To make map downloads more reliable and support resumption, use the android download manager. 
This is necessary for downloading large map files, such as India (1.3G), over unstable connections.

**Comment by pstorch** [comment]
What a pity. The Android DownloadManager can't download to destinations via the SAF Storage Access Framework. 
So I can't use it, or have to sacrifice the map sharing with other apps.

**Comment by dennisguse** [comment]
What about downloading the file via Androids Downloadmanager and then moving it?

**Comment by pstorch** [comment]
That's an option, but would require double storage space temporarily.

**Comment by pstorch** [comment]
I'm thinking about making the internal storage the default map/theme directory for downloads. That would simplify the onboarding of new users. Download maps from within the app only into this internal storage.
Keep the map/theme directory setting for additional (readonly) map/theme sources. Would only be needed by experienced users who share the maps between apps.
