### ISSUE TITLE
Corsican localization for OSMDashboard is now ready on Weblate

### ISSUE THREAD

**Issue by Patriccollu** [OpenTracksApp/OSMDashboard#404]
Hello,

As I found your project interesting, I just completed the **Corsican localization** on [Weblate](https://translate.codeberg.org/projects/open-tracks-osm-dashboard/-/co/).

For your information, I translated _OpenTracks_ two days ago, see issue https://github.com/OpenTracksApp/OpenTracks/issues/1974.

Best regards,
Patriccollu.

**Comment by pstorch** [comment]
Thanks :+1: 
I've merged it in.  You can test it with the next nightly build.

**Comment by dennisguse** [comment]
@pstorch it might be that this locale is not directly accessible and must be set programmatically. At least that's how it looked on my Android 12.

**Comment by pstorch** [comment]
Thank @dennisguse I need to check that

**Comment by Patriccollu** [comment]
Many thanks @dennisguse and @pstorch for your help to solve this problem regarding Corsican locale. I appreciate!

**Comment by pstorch** [comment]
@dennisguse is that already implemented in OT? 
https://github.com/OpenTracksApp/OpenTracks/issues/1970#issuecomment-2295355736
I couldn't find any in-app setting.

I found the `resource.properties` file and enabled the `generateLocaleConfig` in build file. But this only activates the App Info langugae chooser via the launcher and co isn't available.

**Comment by dennisguse** [comment]
I know: https://github.com/OpenTracksApp/OpenTracks/issues/1970#issuecomment-2295355736

**Comment by Patriccollu** [comment]
Hello @pstorch ,

For your information **Corsican** language can now be selected in OpenTracks thanks to @dennisguse  ;-) and a language chooser for all Android versions.

Best regards,
Patriccollu.

**Comment by dennisguse** [comment]
@pstorch we could also send the current locale from OpenTracks.

**Comment by pstorch** [comment]
I borrowed the code from OpenTracks. Now it should be possible to choose corsican also in OSMDashboard.
@dennisguse I was thinking about adding the locale to the dashboard API as you proposed. Could be possible, but OSMDashboard doesn't support the all languages from OT.

**Comment by Patriccollu** [comment]
@pstorch 
Hi Peter,

Thanks a lot! I look forward testing it with the next nightly versione ;-)

Cheers,
Patriccollu.

**Comment by dennisguse** [comment]
Works for me :)
