### ISSUE TITLE
Delete partially downloaded maps

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OSMDashboard#42]
1. Go to download
2. Download any map
3. While downloading: press back
4. File is only partly downloaded, but file not erased

**Comment by pstorch** [comment]
Hm, on my device the Thread continued until the file was downloaded. I guess if it takes too long Android would kill it.
What would be the expectation on back button? Stop the download + cleanup?

**Comment by dennisguse** [comment]
Sounds good to me. Even an additional dialog would be cool.
One additional hint: my phone is in battery saver mode and thus might behave differently.
