### ISSUE TITLE
Can't use it

### ISSUE THREAD

**Issue by irrelevantspechack** [OpenTracksApp/OSMDashboard#427]
I have a recent android phone but when I click on the map on opentracks it open the osmdashboard thatu say 'you haev no offline map configured yet".

But I indicated a folder for offline maps and it has the maps of the opentracks route location.

I don't understand how it is supposed to work.

**Comment by pstorch** [comment]
Sorry to hear. How does your settings dialog look like? You can attach screenshots here.
Do you have selected the downloaded map(s) in Settings / Maps?

**Comment by pstorch** [comment]
Opentracks normally shows elevation gain and loss. Where do you miss it? Maybe open an issue in the OT repo.

**Comment by dennisguse** [comment]
Gain/loss requires a barometer.

**Comment by irrelevantspechack** [comment]
I have a recent samsung flagship, doesn't it should include one/detect it?

**Comment by dennisguse** [comment]
@irrelevantspechack Check your phone and also if it is set up correctly in OpenTracks. 
See settings/sensors/barometer.

Hard to check remotely ;)

**Comment by pstorch** [comment]
Not an issue of OSMDashboard.
