### ISSUE TITLE
Overwrite downloaded maps

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OSMDashboard#43]
If a map was already downloaded and the a new map file is selected with the same name, the old file is not overwritten.
The new map is stored with a (1) suffix and thus not be available in the menu.

**Comment by pstorch** [comment]
Good catch, I haven't checked the folder yet ane didn't see it. That is a problem with the Storage Access Framework. We don't create actual files but documents and the owning application of the folder has the authority about the file extension. 
But I can search if this document already exist and ask the user if it should be deleted first.
