### ISSUE TITLE
Corsican language not kept from one session to another

### ISSUE THREAD

**Issue by Patriccollu** [OpenTracksApp/OSMDashboard#447]
Hello,

I just installed from [StorchP's F-Droid Repo](https://fdroid.storchp.de/fdroid/repo?fingerprint=99985A7E73DCB0B16C9BDDCE7A0B4996F88068AE7C771ED53E217E69CD1FF196):
- the latest OSM Dashboard for OpenTracks (Nightly) version: 2024-Dec-23 00:16:30 UTC / de.storchp.opentracks.osmplugin.nightly_1267
- the latest OpenTracks (Nightly) version 2024-Dec-23 08:17:49 UTC / v4.17.0-1-g82c0f3dcc

When I change the language from Default to Corsican on OpenTracks, it is taken into account and kept from one session to another.

But this is not the case with OSM Dashboard for OpenTracks: the language is changed, but it isn't kept from one session to another. If I close OpenTracks and come back to display a track, OpenTracks is in Corsican but OSM Dashboard came back to default language, French in my case.

On the other hand, the language is properly kept from a registered track to another track, within the same OpenTracks session.

Thanks for your help,
Patriccollu.

**Comment by pstorch** [comment]
Thanks for testing. I can confirm. If OSMDashboard is restarted, the language setting is gone. I guess I have to restore it on Startup.

**Comment by pstorch** [comment]
The `AppLocalesMetadataHolderService` was missing in the manifest. Hope this solves it.
@Patriccollu would be nice if you could test the next nightly build.

**Comment by Patriccollu** [comment]
Thanks a lot Peter! I will do and will keep you informed.
Patriccollu.

**Comment by Patriccollu** [comment]
Latest nightly version `2024-Dec-23 22:17:37 UTC / de.storchp.opentracks.osmplugin.nightly_1269`solved the problem!

Perfect :-)
Patriccollu.

**Comment by Patriccollu** [comment]
![Screenshot_2024-12-24-00-35-24-362_de storchp opentracks osmplugin nightly](https://github.com/user-attachments/assets/39468466-5ddd-4133-a53f-bcc8587b4e17)
