### ISSUE TITLE
OSMDashboard constantly crashes if using downloaded offline maps since 2.0.0

### ISSUE THREAD

**Issue by renegat73** [OpenTracksApp/OSMDashboard#45]
Android 7.1.2 / Moto G4 Play 'harpia'

Since latest Version 2.0.0 installed from FDroid OSMDashboard constantly crashes on use with offline maps.

OSMDashboard offers to download offline Maps from menu.
I downloaded map for germany and tried to open a recorded track from OpenTracks.
'Offline Map Directory' was set accordingly to right location.
Error: 'OSMDashboard was closed/ended.' (Don't know exact translation for error message)
Also tried to download map for state only - same result.
Tried with online map - worked.

Downgraded OSMDashboard to previous version 1.6.0 - offline Maps works again.

**Comment by pstorch** [comment]
Oh, how can I find out what goes wrong here?
Can you download maps manually via your Browser and point the OSMDasboard to the download directory?

Are the maps download correctly? Can you check the downloaded map? Is the size correct? Maybe you can send it to me somehow?

**Comment by renegat73** [comment]
As the downloaded maps work flawless with OSMDashboard 1.6.0 I don't think they are the cause.
They are downloaded from: [here](https://ftp-stud.hs-esslingen.de/Mirrors/download.mapsforge.org/maps/v5/europe/germany/)
Size fits (hessen.map 158MB)
Will try to download map via browser and report back... 

Addenum:
Weird! After upgrading again from 1.6.0 to 2.0.0 OSMDashboard works with offline map too.
I'll keep an eye on it but I assume the issue has vanished now...

**Comment by gdt** [comment]
With an offline map I had downloaded earlier, 2.0.0 works fine for me.  (Just a data point.)

**Comment by pstorch** [comment]
@renegat73 so you still have problems with the 2.0.0 version?

**Comment by pstorch** [comment]
@gdt downloaded maps from within the App don't work?

**Comment by renegat73** [comment]
Yes, it seems 2.0.0 looses the map directory setting on reboot.
The 'maps' setting is reset to OSM:Mapnik and the downloaded map is not shown anymore.
After re-choosing the map-directory and switching the map back to the downloaded map it works again.
Will try to save map to another location...

**Comment by pstorch** [comment]
Hmm, maybe something with the Preferences. Does it make a difference if you choose the directory via the menu or if you get the directory chooser when downloading the first map.

**Comment by renegat73** [comment]
@pstorch: It does not make any difference if I choose the directory via menu or use the directory chooser.

The problem affects LineageOS 14.1,  Android 7.1.2 (Nougat) also as the stock rom google android 7.1.1 and only OSMDashboard 2.0.0
Another phone tested: Nokia 3.1 Android '9' (Pie): exact the same issue! Crashes on call from OpenTracks. The offline map is 'gone' in OSMDashboards settings after reboot till you confirm the map directory again. 
Than it works.

OSMDashboard 1.6.0 is not affected by this bug.

**Comment by pstorch** [comment]
Now I could reproduce. I found something with the Uri permissions of the maps directory. I changed it to WRITE_PERMISSION and removed the READ_PERMISSION. Thought it is included, but somehow only WRITE is not persistable and vanishes after a reboot.

**Comment by pstorch** [comment]
@renegat73 would be nice if you could test the debug APK: https://cloud.railway-stations.org/index.php/s/gHaHJJ9PPmzicNd

**Comment by renegat73** [comment]
@pstorch I installed the debug APK on G4 Play 'harpia' LineageOS 14.1 Android Nougat 7.1.2:
- set the maps directory and chose a map.
Called OSMDashboard from OpenTracks - works.
Rebooted: Works too now! Map Directory/Map settings are saved now, App does not crash anymore.
Will try other phones / ROMs later but issue seems to be gone now.

**Comment by pstorch** [comment]
@renegat73 great, thanks for testing.

**Comment by dennisguse** [comment]
@pstorch: you can also publish apks on Github - you just need to zip them first :)

**Comment by pstorch** [comment]
@dennisguse good to know 🙂
