### ISSUE TITLE
Rendering optimization?

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OSMDashboard#46]
I just realized that OpenTracks has a performance optimization for rendering the graphs.
Precisely, not all TrackPoints are rendered, but only a very limited subset.
This speeds-up the whole rendering process and (I guess) saves some energy.

Would this also be a useful approach for OSMDashboard?
Especially for longer tracks, I have sometimes the impression that the map rendering gets rather sluggish especially while zooming/panning.

The code is in the `TrackDataHub`.

PS: I have no idea how to do this or if it is helpful at all.

**Comment by pstorch** [comment]
Interesting. Downsampling could really improve render speed. I need to look into it and make some tests.
When I read the TrackDataHub correctly it "just" downsamples the TrackPoints evenly to have a max. of 5000 TrackPoints.
I'm thinking if another strategy like the "Trackpoint distance threshold", like described here https://www.gpsvisualizer.com/tutorials/track_filters.html would be better for a Map,

**Comment by dennisguse** [comment]
I can offer an implementation of Douglas-Peucker (already in OpenTracks but not used due to the removal of Google Maps).
It is in `LocationUtils.decimate()`.
I guess it just works - but there are no tests (yet) available.

**Comment by pstorch** [comment]
The Douglas-Peucker algorithm tries to smothen the whole track. Which is applicable when the track is completed. But when the track is currently being recorded and constantly updated, I don't want to redraw the whole track over and over again, see #19.

Maybe I need two different strategies. Or smoothen the partial track when the Activity is started and use a simple distance calculation for updated tracks.

**Comment by dennisguse** [comment]
I forgot that we need online processing :)

What about applying Douglas-Pecker to only older parts of the track?
When you reach 1100 unsmoothed TrackPoints, apply Douglas-Pecker to 1-1000, and then repeat?

**Comment by gdt** [comment]
> I forgot that we need online processing :)
> 
> What about applying Douglas-Pecker to only older parts of the track?
> When you reach 1100 unsmoothed TrackPoints, apply Douglas-Pecker to 1-1000, and then repeat?

I think that makes sense.   But rather than just "repeat", I would say that DP should exclude recent points (perhaps) time and then run only when there are old points, with a constraint that the newest point in the set being simplified is required to be kept.   Then, all points that result, except for that last one are marked as already simplified, and not eligible for reprocessing.

(I think this is only about display and the real data is being kept.)

**Comment by pstorch** [comment]
First test works quite well with 10m tolerance. Loading 4 Tracks with 7 - 15km. The tracks look qood on the map.

```
2020-07-12 10:32:52.033 24240-24240/de.storchp.opentracks.osmplugin.debug D/LatLongUtils: Decimating 1351 points to 65 w/ tolerance = 10.0
2020-07-12 10:32:52.033 24240-24240/de.storchp.opentracks.osmplugin.debug D/MapsActivity: Continue new segment.
2020-07-12 10:32:52.189 24240-24240/de.storchp.opentracks.osmplugin.debug D/LatLongUtils: Decimating 1271 points to 155 w/ tolerance = 10.0
2020-07-12 10:32:52.189 24240-24240/de.storchp.opentracks.osmplugin.debug D/MapsActivity: Continue new segment.
2020-07-12 10:32:52.377 24240-24240/de.storchp.opentracks.osmplugin.debug D/LatLongUtils: Decimating 2033 points to 117 w/ tolerance = 10.0
2020-07-12 10:32:52.377 24240-24240/de.storchp.opentracks.osmplugin.debug D/MapsActivity: Continue new segment.
2020-07-12 10:32:52.404 24240-24240/de.storchp.opentracks.osmplugin.debug D/LatLongUtils: Decimating 2665 points to 124 w/ tolerance = 10.0
2020-07-12 10:32:52.404 24240-24240/de.storchp.opentracks.osmplugin.debug D/MapsActivity: Continue new segment.

```

> When you reach 1100 unsmoothed TrackPoints, apply Douglas-Pecker to 1-1000, and then repeat?

That would mean I need to redraw the the polylines from time to time. At least from the last segment. Does someone really keep the Map open while recording for so long. Going back to OpenTracks and open the Dashboard again would smooth the track automatically. It would be easier to either not smooth at all while recording or simply only add a new TrackPoint if it is over the tolerance (e.g. 10 meters) away from the last TrackPoint.

**Comment by pstorch** [comment]
While working on the track smoothing I found out that I don't handle the pause TrackPoints correctly. I didn't split the polyline at those. Now I do it and see how bad my GPS reception was in the forrest with my old device. A lot of seqments :scream: :

![Screenshot_20200713-233114_OSM Dashboard for OpenTracks](https://user-images.githubusercontent.com/5598124/87355947-8873a000-c561-11ea-8170-b360be4d2a29.jpg)

Let's see next run in the forrest with my newer device :wink:

**Comment by pstorch** [comment]
About smoothing while recording,  in OpenTracks there is a setting called "Recording distance interval". Default is 10m. This sounds similar to what I had in mind. But if OpenTracks already does it, maybe I should draw the TrackPoints while recording just as they come.

**Comment by gdt** [comment]
People can set time/distance recording criteria various ways.  I guess if it turns out that rendering really is slow, while using recording settings people really do use., then it makes sense to optimize.

I use 1s, no distance, on my etrex30 when hiking, because I want the best track possible for mapping later, not because i really care where I was for hiking distance records.   I don't know if people use opentracks for this.

**Comment by pstorch** [comment]
I think I'll do it in two steps. First the track smoothing for finished tracks and later track smoothing for currently recorded tracks (if needed). I'll open a separate issue for that to collect feedback.
