### ISSUE TITLE
Track smoothing / render optimization for live recorded tracks

### ISSUE THREAD

**Issue by pstorch** [OpenTracksApp/OSMDashboard#47]
Follow up on https://github.com/OpenTracksApp/OSMDashboard/issues/46.

Is track smoothing needed/wanted for tracks which are currently being recorded?

**Comment by pstorch** [comment]
Issues with smoothing of currently recorded tracks:

- Douglas-Peuker takes several TrackPoints into account, that would mean to eventually remove polylines from the current track and redraw them when new TrackPoints are send to OSMDashboard
  - a subvariant of this would be to only smooth the live track if a certain number of new TrackPoints are reached (e.g. 1000)
- A simple track smoothing algorithm is already implemented in OpenTracks (Recording distance interval), which defaults to 10m and only records a TrackPoint if the 10m from the last TrackPoint are reached. So for me it doesn't make sense to duplicate this simple track smoothing in OSMDashBoard.

**Comment by dennisguse** [comment]
Contains some relevant information: https://github.com/OpenTracksApp/OSMDashboard/issues/46#issuecomment-658703619

From an OpenTracks perspective: while recording, we are doing some optimization like only record locations that cross a certain distance threshold, ignore inaccurate locations etc. Under some settings, we even change the location request interval dynamically (adapt for battery live).
In the end, I am not sure why some of them were implemented and fun question is actually if we still need them (or if they are just making our life more complicated).

**Comment by dennisguse** [comment]
@pstorch This was implemented in v2.1.0, right?

**Comment by pstorch** [comment]
Only for finished tracks. This Ticket is for currently recorded tracks.

**Comment by pstorch** [comment]
@dennisguse do you think we still need to do something for the live recorded tracks?

**Comment by dennisguse** [comment]
To be honest: don't know; cycling season starts in April again ;)
And for local hiking, I don't need a map.
So, let's close and get back to it, when it bothers us again. ><
