### ISSUE TITLE
Render waypoints

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OSMDashboard#48]
Can we also render waypoints (the markers that a user might have created while tracking) on the map?

**Comment by pstorch** [comment]
Good idea, with access to the photos. Then we need to forward the waypoints uri as well.

**Comment by dennisguse** [comment]
Damn - that is an awesome idea!
The photoUrls might be a problem - we need to give access to each of them and also pass all the URLs.
I hope, we don't hit an Android internal limit on how many URLs we can pass :)

**Comment by pstorch** [comment]
Grant read access to a base URL for the photos is not an option for the Dashboard, right? Because then only one additional URL would be needed.

**Comment by dennisguse** [comment]
I am not sure ;)
Let's try it out - it was just a wild guess from side (should have done some research beforehand).

**Comment by dennisguse** [comment]
Or we could link back to OpenTracks using App links: https://developer.android.com/studio/write/app-link-indexing
(at least to show the details/pictures of the markers)

**Comment by pstorch** [comment]
Or simply call the MarkerDetailActivity via Intent?

**Comment by pstorch** [comment]
I'll look at it.

**Comment by pstorch** [comment]
Calling the MarkerDetailActivity from Waypoint marker on the map works like a charm. It works so good, that I wouldn't add any popup dialog in OSMDashboard and call the MarkerDetailActivity directly when tapping on the marker.

What Icon should be used? There is this blue pin from Google Maps, but I'm not sure, if the OSMDashboard should load the icon bitmaps from external URLs. Should we just show the new orange pin?

**Comment by dennisguse** [comment]
Cool! The orange pin would be perfect. I will replace the current blue pin in OpenTracks tomorrow. I guess the color needs some fine tuning - but that's it.

**Comment by dennisguse** [comment]
I left the color of the push pin as it was - we can change it later, but for now it far better than the blue one.
I just have to get used to it :)

**Comment by dennisguse** [comment]
:1st_place_medal:
