### ISSUE TITLE
Enable picture-in-picture mode?

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OSMDashboard#49]
i am not sure this is useful, but why not ><

https://developer.android.com/guide/topics/ui/picture-in-picture

**Comment by pstorch** [comment]
@dennisguse you mean the map floating as a pip over OpenTracks? Sounds interesting :smile:

**Comment by dennisguse** [comment]
Exactly :)
Probably not really useful, but fancy ><

**Comment by dennisguse** [comment]
Works for API24+.
I just tested it with TrackListActivity ><

```
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                    this.enterPictureInPictureMode();
                }
```

```
        <activity android:name=".TrackListActivity"
            android:supportsPictureInPicture="true">
```
![Screenshot_20200717-212751_Trebuchet](https://user-images.githubusercontent.com/2820825/87824025-cda31500-c874-11ea-98ca-3ae238b6fa79.png)

**Comment by pstorch** [comment]
I'm playing around with it. Looks nice:
![Screenshot_20200718-232447](https://user-images.githubusercontent.com/5598124/87862311-d10acf00-c94e-11ea-8850-d9ccbfa58cad.jpg)


But has some quirks, e.g. map not updating while recording. I have to look into it some more if time permits.

**Comment by dennisguse** [comment]
The underlying activity is paused, when entering PIP.
Could it be that this is interfering: https://github.com/OpenTracksApp/OSMDashboard/blob/3dee570baa041fc2a586b1cfbd296ff93d5088c4/src/main/java/de/storchp/opentracks/osmplugin/MapsActivity.java#L590

More details are available here: https://developer.android.com/guide/topics/ui/picture-in-picture#continuing_playback

**Comment by dennisguse** [comment]
@pstorch Do you have a branch with your changes?
I would be interested to use this feature next while cycling :)

**Comment by pstorch** [comment]
Yes, but it was not pushed yet. Now it's here: https://github.com/OpenTracksApp/OSMDashboard/tree/pip

**Comment by dennisguse** [comment]
I will push some small improvements in the evening. Stay tuned ;)

**Comment by dennisguse** [comment]
Tuned ><

Changes:
* hide unnecessary UI elements in PiP mode
* OpenTracks reports if the current track is recording
* OpenTracks starts Dashboard on the same stack (so, that back button works as expected).
  Otherwise the Dashboard gets it's own card in the activity switcher and when selected it gets restarted with the _original_ intent.

**Comment by dennisguse** [comment]
PPS: With Android 11 the PiP window can also be resized :100:
