### ISSUE TITLE
Release v2.3.0?

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OSMDashboard#59]
I would love to get the PiP feature :)

**Comment by pstorch** [comment]
I haven't tested it much, but if you say it works for you, I'll glad to release it.

**Comment by dennisguse** [comment]
I used the PiP mode extensively during the weekend while cycling.
Was really cool for navigation :)

**Comment by pstorch** [comment]
Release tagged and playstore upload running.
