### ISSUE TITLE
Segments are ignored

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OSMDashboard#6]
OpenTracks splits a track into segments as it might happen that a track was paused for some time or the GPS signal was too bad.
In such a case, OpenTracks inserts "fake" trackpoints (i.e., PAUSE_LATITUDE or RESUME_LATITUDE).
And these are also provided to OSMDashboard and should use these as segment markers.
At the moment, these are just ignored as the coordinates are invalid.

The issue was observed here: https://github.com/OpenTracksApp/OpenTracks/issues/125

**Comment by pstorch** [comment]
I'll have a look at it
