### ISSUE TITLE
Auto-rotate map based on your compass heading.

### ISSUE THREAD

**Issue by rgmf** [OpenTracksApp/OSMDashboard#61]
Do you find useful this option? So users could select between:
- North-up.
- Track-up.

**Comment by pstorch** [comment]
That's another good feature.

**Comment by pstorch** [comment]
Arrow and Map rotation together are mind blowing. 
For example when the arrow points to north and the map is rotated according to the compass, should the arrow point to the real world north or the map north? Same with movement direction: should it be according the direction on the map or the real world direction?

**Comment by rgmf** [comment]
What I'd like is arrow points to north in the map. I mean, arrow always points up in the screen of the phone and the map rotates. So compass will use to rotate the map but not the arrow that always points up.

But, I don't know how difficult it is and if it worth it.

**Comment by pstorch** [comment]
Rotating the arrow and rotating the map is technically not a problem. I just need to be sure in what direction :wink: 

I have the following settings now:

1. Arrow rotation (already implemented)
  - Point to north (physically)
  - Point to moving direction

2. Map rotation
  - Static (North always on top)
  - Rotate map to physical north: if you look with your device south, map north is at bottom of device
  - Rotate map to moving direction, if you move east, map north is to the left of your device. 

And now we can combine both, which has some interesting effects:
- For example Arrow points to north, map north fixed at top of device (as default previously): in this setting the arrow and the map are only in sync, when you hold your device to north.
- Second example: Arrow points in moving direction and Map is rotated also in moving direction. If you now move east, but hold your device south, then the line is drawn from bottom to top of your device, but the arrow points left.

@rgmf your example "arrow that always points up." Is that an arrow without functionality or do you mean "Arrow in moving direction" when you hold your device in moving direction?

**Comment by rgmf** [comment]
@pstorch like in navigation GPS apps. Last week I complete an unknown route and I had to use OSMDashboard to guide me, that's why I think is useful a behaviour like navigation GPS. So here arrow is an arrow without functionality like you say.

**Comment by pstorch** [comment]
Ok, I guess the navigation App assumes you also hold your device in the direction you travel.
I think I will do it similar.

**Comment by rgmf** [comment]
> Ok, I guess the navigation App assumes you also hold your device in the direction you travel.
> I think I will do it similar.

I guess so too.
