### ISSUE TITLE
Dependabot?

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OSMDashboard#67]
I activated dependabot (now with useful configuration) for OpenTracks.
Should I also do it here?

**Comment by pstorch** [comment]
Sure 👍

**Comment by dennisguse** [comment]
Follow-up thing: we don't have tests in OSMDashboard, we could still try to compile it via Github Actions.
Just to check if the dependency updates broke something.
Again: we can use same config as OpenTracks.
