### ISSUE TITLE
Introduce offline only variant of OSMDashboard

### ISSUE THREAD

**Issue by pstorch** [OpenTracksApp/OSMDashboard#70]
From: https://github.com/OpenTracksApp/OpenTracks/issues/412#issuecomment-688513847
For users with high requirements on privacy a version of OSMDashboard without internet access would be appreciated.

Build a variant of OSMDashboard without internet permission. This can probably be achieved by a build flavor.

**Comment by gdt** [comment]
Lack of internet permission would be nice, but I think the main thing has been achieved, which is no internet use without affirmative configuration.   The question of whether the user is willing to trust the app authors is a crucial one, and while I am in favor of minimal permissions, I do not generally find it safe to run code from untrustworthy sources with sandboxing.

**Comment by dennisguse** [comment]
I don't know the state of other Android versions, but on my LineageOS I can disable/restrict Internet access per app. So I am okay.

**Comment by pstorch** [comment]
On Samsung Stock ROM 🙈 I cannot remove internet permission per App.

**Comment by pstorch** [comment]
> I think the main thing has been achieved

So it's not a high priority, only a nice to have, to build an extra app without internet permission.

**Comment by pstorch** [comment]
It's available now on F-Droid: https://f-droid.org/en/packages/de.storchp.opentracks.osmplugin.offline/
