### ISSUE TITLE
Performance related question

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OSMDashboard#71]
I was wondering why the zoom/pan performance is not that cool on a relatively modern device (i.e., Pixel 1) and I was then reading the MapsActivity.
I stumpled upon the TileCache and was wondering, why do we have multiple? One per layer?
We seemling only use `tileCaches.get(0)` (for actual background map).
Would we also need one for the TrackPoints?

https://github.com/OpenTracksApp/OSMDashboard/blob/d72723f1292a747a359eeb44ebe5e1612644c2ba/src/main/java/de/storchp/opentracks/osmplugin/MapsActivity.java#L216

PS: Just thinking aloud :)

**Comment by pstorch** [comment]
I need to look into it. I'm not that familiar with the tile cache. Probably there is something to improve.

**Comment by dennisguse** [comment]
i did some digging and mapsforge renders single threaded by default.
Back in 2015 they had some trouble with multi-threading, so they disabled it by default.

More infos are here.
https://github.com/mapsforge/mapsforge/blob/02134d0085eba7aa7589817a5973829201000351/mapsforge-core/src/main/java/org/mapsforge/core/util/Parameters.java

I activated multi-threading in startup and it helps (zoom and pan get more fluent, but there is still room for improvement).
But I did no parameter tweaking so far.
This can be overridden by:

```
package de.storchp.opentracks.osmplugin;

import android.app.Application;
import android.os.StrictMode;
import android.util.Log;

import org.mapsforge.core.util.Parameters;

public class Startup extends Application {

    private static final String TAG = Startup.class.getSimpleName();

    @Override
    public void onCreate() {
        super.onCreate();
        Parameters.NUMBER_OF_THREADS = Runtime.getRuntime().availableProcessors() + 1;
}
```

**Comment by pstorch** [comment]
Hmm, as I don't have the performance issues, this will be hard to verify by me. And reading the linked issue, I fear a bit the described render issues. 
Maybe as a configurable option, so it can be turned off in case it makes trouble.

**Comment by dennisguse** [comment]
Then your phone is faster or the area might contain less detail. I seemingly get this issue due to the background map. Zoom/pan is not okayisch without.

And AAT sets a thread count: https://github.com/bailuk/AAT/blob/b1f2180e4d4be97e8c6f9e7e3c47e60fc20c524c/app/src/main/java/ch/bailu/aat/preferences/map/SolidRendererThreads.java

Let me create a video showing the problem as well as a complete setup description.

**Comment by pstorch** [comment]
Do you use online or offline maps?
Is map rotation activated?

**Comment by dennisguse** [comment]
Offline, no rotation, post recording, and Berlin (a lot of detail in map).

**Comment by pstorch** [comment]
I added multihreadding for the map rendering. I don't see a difference on my device. @dennisguse please give it a try.

**Comment by pstorch** [comment]
After I tested a while I got some rendering issues (gray tiles). But it didn't matter If I enable or disable multi threadding.

**Comment by pstorch** [comment]
There is also a possibility to add a StyleMenu as in https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/StyleMenuMapViewer.java and give the user the possibility to remove elements from the map which are not needed to be rendered.

**Comment by pstorch** [comment]
@dennisguse should we release that for now?

**Comment by pstorch** [comment]
@dennisguse is it ok for now?

**Comment by dennisguse** [comment]
Way better!
I still have the feeling that too much happens in the UI thread, but that is just a feeling ;)
Mainly if the map is using the compass as direction.
