### ISSUE TITLE
Permission to access downloads

### ISSUE THREAD

**Issue by jpschewe** [OpenTracksApp/OSMDashboard#74]
I have downloaded since maps through the app to my downloads folder. I went to the menu in the app and selected Map Directory, I was prompted to see my downloads directory. There is a button at the bottom of the page to allow access to downloads. I click this and I'm sent back to the main screen. I select Map Directory again and I am prompted for the permission again. Is this expected?

**Comment by pstorch** [comment]
Hi @jpschewe this button is provided by your file manager. OSMDashboard is requesting access to a directory. I guess the file manager doesn't check if the access to this directory was already granted.

**Comment by jpschewe** [comment]
OK, so once I have granted the permission, then the directory is set properly. Correct?

Should I see anything different in the app once I have this directory set and maps downloaded to that directory?

**Comment by pstorch** [comment]
After choosing and granting access to a directory you should be able to download maps to that directory and you should see and be able to select the maps from that directory via the Maps menu.

**Comment by jpschewe** [comment]
Got it, then everything is working. Thank you for your time.
