### ISSUE TITLE
reduce the width of the track

### ISSUE THREAD

**Issue by PhantomO2** [OpenTracksApp/OSMDashboard#79]
Using OSM dashboard offline. Can you please reduce the width of the blue tracks to pencil thin. These track are too bold and I have to zoom in alot to actually see the tracks. Btw, so far OSM dashboard offline is working perfectly fine. Great job guys. And thanks for making this app privacy friendly.  Pic 1:- the track that I usually get when I open track with OSM dashboard offline. PIC 2:- zoomed out version of complete track. PIC 3:- zoomed in version of the start of the track.
![afcf2fd7-413b-4520-83c0-7eec4ad46d29](https://user-images.githubusercontent.com/70547483/96260617-e5f20f80-0fdc-11eb-8748-9df3ed209a40.png)
![b25510c6-d81d-4bff-9dd2-5089c88a9632](https://user-images.githubusercontent.com/70547483/96260653-eee2e100-0fdc-11eb-9e29-99fd65d4eaae.png)
![0acef8cc-be57-4d8c-a599-542286ff6d7b](https://user-images.githubusercontent.com/70547483/96260678-f6a28580-0fdc-11eb-98e7-ed3f9a6d23c4.png)

**Comment by pstorch** [comment]
Thanks for the feedback, I'll take a look at the stroke width.

**Comment by pstorch** [comment]
@PhantomO2 what do you think about this?

![image](https://user-images.githubusercontent.com/5598124/96276153-e7b6d580-0fd2-11eb-9965-2ba453dbc5b1.png)

![image](https://user-images.githubusercontent.com/5598124/96276207-f604f180-0fd2-11eb-8880-b62d630c7cc7.png)

Even with a Map rendered, it looks better with the thinner lines. I like it.
I think I'll make it configurable, so users can set the stroke width how they like it.

**Comment by dennisguse** [comment]
We can make this also dependent on the configured display size (the Android settings): https://support.google.com/accessibility/android/answer/6006972?hl=en

**Comment by pstorch** [comment]
It already takes the displayScaleFactor into account.

**Comment by PhantomO2** [comment]
> I think I'll make it configurable, so users can set the stroke width how they like it.

Awesome!!!!

**Comment by pstorch** [comment]
@PhantomO2 have you got the update? What is your preferred stroke width setting?

**Comment by PhantomO2** [comment]
@pstorch, Mine is 2. And thanks for the update!!!
