### ISSUE TITLE
instructions on where to put offline maps

### ISSUE THREAD

**Issue by nutpantz** [OpenTracksApp/OSMDashboard#8]
instructions on where to put offline maps would be nice.
A directory picker so we can use internal or sd card storage would be nicer.

**Comment by pstorch** [comment]
Instructions can be improved, right.

A directory chooser is available,  but only for external storage.
Do you mean you want to be able to put the files on the App internal storage? On my device it would be something like this path "/storage/emulated/0/Android/data/de.storchp.opentracks.osmplugin/files".

**Comment by nutpantz** [comment]
To be honest i would like to pick the same directory that orux map uses for map files, that way i don't have to have 2 copies of the same maps. 
But that is unlikely...
So instructions on how to use the directory picker (for the external sd) and where to put the maps would be adequate.

**Comment by pstorch** [comment]
@nutpantz I've added some description about the offline maps and made it more visible. It's also in the README. I don't know if this is good enough. Feedback welcome.

I tried to check out orux map, but as it is a paid app, I stopped. I only saw in the app description that orux map can work with different map formats. This app is limited to Mapsforge type of maps.
