### ISSUE TITLE
Add inbuilt compass (feature)

### ISSUE THREAD

**Issue by JahidFariz** [OpenTracksApp/OSMDashboard#84]

**Comment by dennisguse** [comment]
What do you need it for? To just see a compass: we have in OSMDashboard. 
Does this fit your needs?

**Comment by pstorch** [comment]
@JahidFariz in the menu you can set "Arrow as compass", then the arrow of your position/last trackpoint is pointing to north. You can also rotate the map to point to north.

**Comment by pstorch** [comment]
No response, closing
