### ISSUE TITLE
Make map movement animation transition smooth. (Feature and question)

### ISSUE THREAD

**Issue by JahidFariz** [OpenTracksApp/OSMDashboard#85]

**Comment by pstorch** [comment]
@JahidFariz how is your "Recording distance interval" setting in OpenTracks? The default is 10 meters, so only after you moved 10 meters a new trackpoint is recorded and send to OSMDashboard. The the map "jumps" to the new position. You can set it down to 1 meter, then the map movement should be more smooth.

**Comment by pstorch** [comment]
I think instead of "jumping" to the new trackpoint I can ask the map to animate to the new trackpoint. Need to try it.

**Comment by pstorch** [comment]
@JahidFariz I found a way to animate the map movement to a new trackpoint. It's not really smooth, but it's not fully jumping anymore. Do you want to give it a try? I can build a debug APK.

**Comment by JahidFariz** [comment]
Sure I'll, @pstorch

**Comment by pstorch** [comment]
@JahidFariz great, here you go:

[OpenTracksOSMPlugIn-full-debug.zip](https://github.com/OpenTracksApp/OSMDashboard/files/5625244/OpenTracksOSMPlugIn-full-debug.zip)

**Comment by pstorch** [comment]
It's implemented some time ago
