### ISSUE TITLE
[Feature Request] Merge with OpenTracks

### ISSUE THREAD

**Issue by mbnoimi** [OpenTracksApp/OSMDashboard#87]
Hi,

I suggest merging both projects in a single project or at least merge the binaries in a single APK file.

I use both of OSMDashboard and OpenTracks on a daily basis, and I'm still unable to understand why both of them are separated!

**Comment by gdt** [comment]
Failure to understand is not a valid argument for combining.   It seems obvious that having OpenTracks and various dashdboards separated enables innovation/choice/etc and that this sort of plug-in architecture is what many projects either do or should aspire to.

You didn't explain if you are having any kind of problem.

**Comment by pstorch** [comment]
Main reason is privacy and trust.
OpenTracks collects your location. For many users this is very sensitive. To be sure this does not leak without the will of the user, OpenTracks has no internet and no file system permission.
The OSMDashboard on the other hand has no location permission. So it is really in the hands of the user what to share and which risk to take.
For some it might look paranoid, for others it is essential. I also had to learn that. 
I hope it makes the reasoning behind this design a little bit understandable.

**Comment by mbnoimi** [comment]
> For some it might look paranoid, for others it is essential. I also had to learn that.
> I hope it makes the reasoning behind this design a little bit understandable.

Good point thanks for the response.

**Comment by Lee-Carre** [comment]
> I'm still unable to understand why both of them are separated

Modularity & (other) [sound design principles](http://www.catb.org/esr/writings/taoup/).

What you advocate is a major cause of software-bloat.
