### ISSUE TITLE
Use OSMand+ maps

### ISSUE THREAD

**Issue by rogercreagh** [OpenTracksApp/OSMDashboard#90]
I have OSMAnd+ installed amd would like to use the offline maps I already have downloaded for that app. They are on SDcard in folder Android/data/net.osmand.plus/files and are in obf format.
I have tried pointing the map directory at that folder but nothing appears and it just says "you have no offline map configured yet"
Is it not possible to use OSMand maps? I'm not going to double up on downloading a different set of maps just for this. Easier to export the track and load into the full app, but a bit clunky.

**Comment by pstorch** [comment]
I'm sorry, the underlying library mapsforge, which is used by this app, doesn't support the map format of OSMand+.

**Comment by gdt** [comment]
Which could also be put:
  * Maybe someone (@rogercreagh perhaps :-) could submit changes to mapsforge to also support osmand format?
  * Maybe someone could write a library with the same interface as mapsforge that is like mapsforge but for osm.

As for me, mapsforge format for my region is only 0.5G, so I don't mind having that and osmand format.

**Comment by rogercreagh** [comment]
Oh, that's a shame. I though from the name that it was an interface to OpenStreetMap. ca va :man_shrugging: uninstall.

**Comment by rogercreagh** [comment]
[quote]Maybe someone (@rogercreagh perhaps :-) could submit changes to mapsforge to also support osmand format?[/quote]

Sorry, not worth the effort, better things to do. Its only a minor irritation, simpler just to export the track from OpenTracks direct to OSMand+. The reason for using OpenTracks is that it has much lower power implications than keeping a full mapping app recording all day. Can afford to fire up OSMand when stopping for cakey-tea and the shut it down when back on the road.
I'll close this issue as its not really an issue.

**Comment by pstorch** [comment]
Sorry for your disappointment, but it's still true, this app uses OpenStreetMap maps. But in mapsforge format not in OSMand+ Format.

**Comment by dennisguse** [comment]
@rogercreagh From a power consumption perspective OSMAnd+ will be at a disadvantage.
We transfer the data as GPX or KML to other applications that do not implement the cursor-based approach like OSMDashboard.
So, OpenTracks encodes the data into a really big data structure (compared to transferring it via a database cursor) and then OSMAnd+ needs to decode the data.
In addition, you have to wait longer (as the data transfer is way slower) and therefore consume even more energy as the display is usually on.

**Comment by rogercreagh** [comment]
That was exactly my point. OpenTracks for logging is better than using OSMand+ (or any other mapping app) because they consume massive amounts of power and flatten a tablet battery in about 5hrs. My use case is not real time mapping - after all who wants to wander or pedal around the real world with their eyeballs glued to a screen.
Having got the track at the end of a day (or over lunch) I want to review it on a decent mapping app, at which point I'm no longer moving around and probably have a power supply available.
If OSMdashboard could work with the main maps then it would be useful for a quick review, but otherwise pointless for me. Others who want to see a map on the go would find it useful I'm sure.
'Nuff said, I think.
