### ISSUE TITLE
Release 2.9.0 with new OpenTracks API v2?

### ISSUE THREAD

**Issue by pstorch** [OpenTracksApp/OSMDashboard#92]
@dennisguse should I already realease OSMDashboard with support for the OpenTracks API v2?

**Comment by dennisguse** [comment]
Yes!
Thanks for keeping that in mind.
Just now I am trying to figure out the GPX thing and then we could release OpenTracks mid next week.

**Comment by pstorch** [comment]
Published on Google Play and tagged for F-Droid :wink:
